const ALL_QUESTIONS = {
  does: [
    {sentence:"She works at a hospital every day.",question:"Does she work at a hospital every day?",why:"'She' es 3ra persona singular presente → Does + sujeto + verbo base"},
    {sentence:"He plays soccer on weekends.",question:"Does he play soccer on weekends?",why:"'He' es 3ra persona singular presente → Does + sujeto + verbo base"},
    {sentence:"The dog barks at strangers.",question:"Does the dog bark at strangers?",why:"'The dog' es 3ra persona singular → Does + sujeto + verbo base"},
    {sentence:"Maria likes coffee in the morning.",question:"Does Maria like coffee in the morning?",why:"'Maria' es 3ra persona singular → Does + sujeto + verbo base"},
    {sentence:"The store closes at nine.",question:"Does the store close at nine?",why:"'The store' es singular → Does + sujeto + verbo base"},
    {sentence:"John speaks two languages.",question:"Does John speak two languages?",why:"'John' es 3ra persona singular → Does + sujeto + verbo base"},
    {sentence:"She reads books every night.",question:"Does she read books every night?",why:"'She' es singular → Does + sujeto + verbo base"},
    {sentence:"The bus arrives at eight.",question:"Does the bus arrive at eight?",why:"'The bus' es singular → Does + sujeto + verbo base"},
    {sentence:"He knows the answer.",question:"Does he know the answer?",why:"'He' es 3ra persona singular presente → Does"},
    {sentence:"The baby sleeps a lot.",question:"Does the baby sleep a lot?",why:"'The baby' es singular → Does"},
    {sentence:"She teaches math at school.",question:"Does she teach math at school?",why:"'She' es 3ra persona singular → Does"},
    {sentence:"It rains a lot in November.",question:"Does it rain a lot in November?",why:"'It' es 3ra persona singular → Does"},
    {sentence:"He drives to work every day.",question:"Does he drive to work every day?",why:"'He' es singular → Does"},
    {sentence:"The cat eats fish.",question:"Does the cat eat fish?",why:"'The cat' es 3ra persona singular → Does"},
    {sentence:"She sings in the choir.",question:"Does she sing in the choir?",why:"'She' es 3ra persona singular → Does"},
    {sentence:"The machine works properly.",question:"Does the machine work properly?",why:"'The machine' es singular → Does"},
    {sentence:"He studies at night.",question:"Does he study at night?",why:"'He' es 3ra persona singular → Does"},
    {sentence:"The river flows to the sea.",question:"Does the river flow to the sea?",why:"'The river' es singular → Does"},
    {sentence:"She enjoys dancing.",question:"Does she enjoy dancing?",why:"'She' es 3ra persona singular → Does"},
    {sentence:"The boy runs fast.",question:"Does the boy run fast?",why:"'The boy' es singular → Does"},
    {sentence:"He writes poems.",question:"Does he write poems?",why:"'He' es 3ra persona singular → Does"},
    {sentence:"She lives near the park.",question:"Does she live near the park?",why:"'She' es 3ra persona singular → Does"},
    {sentence:"The company sells software.",question:"Does the company sell software?",why:"'The company' es singular → Does"},
    {sentence:"He cooks dinner for his family.",question:"Does he cook dinner for his family?",why:"'He' es 3ra persona singular → Does"},
    {sentence:"The alarm rings at six.",question:"Does the alarm ring at six?",why:"'The alarm' es singular → Does"},
    {sentence:"She paints landscapes.",question:"Does she paint landscapes?",why:"'She' es 3ra persona singular → Does"},
    {sentence:"The train stops here.",question:"Does the train stop here?",why:"'The train' es singular → Does"},
    {sentence:"He remembers her birthday.",question:"Does he remember her birthday?",why:"'He' es 3ra persona singular → Does"},
    {sentence:"The child loves ice cream.",question:"Does the child love ice cream?",why:"'The child' es singular → Does"},
    {sentence:"She volunteers on Saturdays.",question:"Does she volunteer on Saturdays?",why:"'She' es 3ra persona singular → Does"},
  ],
  do: [
    {sentence:"They play basketball after school.",question:"Do they play basketball after school?",why:"'They' es plural → Do + sujeto + verbo base"},
    {sentence:"You speak English well.",question:"Do you speak English well?",why:"'You' siempre usa Do → Do + sujeto + verbo base"},
    {sentence:"We eat lunch together.",question:"Do we eat lunch together?",why:"'We' es plural → Do + sujeto + verbo base"},
    {sentence:"The children like cartoons.",question:"Do the children like cartoons?",why:"'The children' es plural → Do"},
    {sentence:"I need more time.",question:"Do I need more time?",why:"'I' usa Do → Do + sujeto + verbo base"},
    {sentence:"They work in the same office.",question:"Do they work in the same office?",why:"'They' es plural → Do"},
    {sentence:"You understand the lesson.",question:"Do you understand the lesson?",why:"'You' usa Do → Do + sujeto + verbo base"},
    {sentence:"We go to the gym on Mondays.",question:"Do we go to the gym on Mondays?",why:"'We' es plural → Do"},
    {sentence:"The students study hard.",question:"Do the students study hard?",why:"'The students' es plural → Do"},
    {sentence:"You know her name.",question:"Do you know her name?",why:"'You' usa Do → Do + sujeto + verbo base"},
    {sentence:"They travel every summer.",question:"Do they travel every summer?",why:"'They' es plural → Do"},
    {sentence:"We have enough money.",question:"Do we have enough money?",why:"'We' es plural → Do"},
    {sentence:"You like this music.",question:"Do you like this music?",why:"'You' usa Do → Do"},
    {sentence:"They live near the school.",question:"Do they live near the school?",why:"'They' es plural → Do"},
    {sentence:"I look tired today.",question:"Do I look tired today?",why:"'I' usa Do → Do"},
    {sentence:"We need to leave now.",question:"Do we need to leave now?",why:"'We' es plural → Do"},
    {sentence:"They cook their own meals.",question:"Do they cook their own meals?",why:"'They' es plural → Do"},
    {sentence:"You remember my address.",question:"Do you remember my address?",why:"'You' usa Do → Do"},
    {sentence:"The dogs bark at night.",question:"Do the dogs bark at night?",why:"'The dogs' es plural → Do"},
    {sentence:"We watch movies on Fridays.",question:"Do we watch movies on Fridays?",why:"'We' es plural → Do"},
    {sentence:"They speak Spanish at home.",question:"Do they speak Spanish at home?",why:"'They' es plural → Do"},
    {sentence:"I need help with this.",question:"Do I need help with this?",why:"'I' usa Do → Do"},
    {sentence:"You want more coffee.",question:"Do you want more coffee?",why:"'You' usa Do → Do"},
    {sentence:"They enjoy hiking.",question:"Do they enjoy hiking?",why:"'They' es plural → Do"},
    {sentence:"We arrive late sometimes.",question:"Do we arrive late sometimes?",why:"'We' es plural → Do"},
    {sentence:"The birds sing in the morning.",question:"Do the birds sing in the morning?",why:"'The birds' es plural → Do"},
    {sentence:"They read the newspaper.",question:"Do they read the newspaper?",why:"'They' es plural → Do"},
    {sentence:"You feel better now.",question:"Do you feel better now?",why:"'You' usa Do → Do"},
    {sentence:"We have class tomorrow.",question:"Do we have class tomorrow?",why:"'We' es plural → Do"},
    {sentence:"They run every morning.",question:"Do they run every morning?",why:"'They' es plural → Do"},
  ],
  did: [
    {sentence:"She called her mother last night.",question:"Did she call her mother last night?",why:"Pasado simple → Did + sujeto + verbo base (sin -ed)"},
    {sentence:"He visited the museum yesterday.",question:"Did he visit the museum yesterday?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"They watched a movie last Friday.",question:"Did they watch a movie last Friday?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"Maria cooked dinner last night.",question:"Did Maria cook dinner last night?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"The students passed the exam.",question:"Did the students pass the exam?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"She went to the doctor last week.",question:"Did she go to the doctor last week?",why:"Pasado simple (went → go) → Did + sujeto + verbo base"},
    {sentence:"He finished his homework.",question:"Did he finish his homework?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"We saw a great show.",question:"Did we see a great show?",why:"Pasado simple (saw → see) → Did + sujeto + verbo base"},
    {sentence:"The team won the match.",question:"Did the team win the match?",why:"Pasado simple (won → win) → Did + sujeto + verbo base"},
    {sentence:"She bought a new dress.",question:"Did she buy a new dress?",why:"Pasado simple (bought → buy) → Did + sujeto + verbo base"},
    {sentence:"He wrote a long email.",question:"Did he write a long email?",why:"Pasado simple (wrote → write) → Did + sujeto + verbo base"},
    {sentence:"They traveled to Europe last year.",question:"Did they travel to Europe last year?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"She found her keys.",question:"Did she find her keys?",why:"Pasado simple (found → find) → Did + sujeto + verbo base"},
    {sentence:"He ate breakfast this morning.",question:"Did he eat breakfast this morning?",why:"Pasado simple (ate → eat) → Did + sujeto + verbo base"},
    {sentence:"The class started late.",question:"Did the class start late?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"She left the meeting early.",question:"Did she leave the meeting early?",why:"Pasado simple (left → leave) → Did + sujeto + verbo base"},
    {sentence:"They moved to a new apartment.",question:"Did they move to a new apartment?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"He took the bus to work.",question:"Did he take the bus to work?",why:"Pasado simple (took → take) → Did + sujeto + verbo base"},
    {sentence:"She studied for three hours.",question:"Did she study for three hours?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"The dog ran away.",question:"Did the dog run away?",why:"Pasado simple (ran → run) → Did + sujeto + verbo base"},
    {sentence:"They sang at the concert.",question:"Did they sing at the concert?",why:"Pasado simple (sang → sing) → Did + sujeto + verbo base"},
    {sentence:"He paid the bill.",question:"Did he pay the bill?",why:"Pasado simple (paid → pay) → Did + sujeto + verbo base"},
    {sentence:"She read the whole book.",question:"Did she read the whole book?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"They helped their neighbor.",question:"Did they help their neighbor?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"He forgot his umbrella.",question:"Did he forget his umbrella?",why:"Pasado simple (forgot → forget) → Did + sujeto + verbo base"},
    {sentence:"She drank too much coffee.",question:"Did she drink too much coffee?",why:"Pasado simple (drank → drink) → Did + sujeto + verbo base"},
    {sentence:"They arrived on time.",question:"Did they arrive on time?",why:"Pasado simple → Did + sujeto + verbo base"},
    {sentence:"He lost his wallet.",question:"Did he lose his wallet?",why:"Pasado simple (lost → lose) → Did + sujeto + verbo base"},
    {sentence:"She met her old friend.",question:"Did she meet her old friend?",why:"Pasado simple (met → meet) → Did + sujeto + verbo base"},
    {sentence:"The kids played outside all day.",question:"Did the kids play outside all day?",why:"Pasado simple → Did + sujeto + verbo base"},
  ],
  is: [
    {sentence:"She is a doctor.",question:"Is she a doctor?",why:"'She' es 3ra persona singular, verbo 'to be' presente → Is + sujeto"},
    {sentence:"He is very tired.",question:"Is he very tired?",why:"'He' es singular, verbo 'to be' → Is + sujeto"},
    {sentence:"The book is on the table.",question:"Is the book on the table?",why:"'The book' es singular, to be presente → Is + sujeto"},
    {sentence:"Maria is from Costa Rica.",question:"Is Maria from Costa Rica?",why:"'Maria' es 3ra persona singular → Is + sujeto"},
    {sentence:"The weather is nice today.",question:"Is the weather nice today?",why:"'The weather' es singular → Is + sujeto"},
    {sentence:"She is ready to leave.",question:"Is she ready to leave?",why:"'She' es 3ra persona singular → Is"},
    {sentence:"The store is open.",question:"Is the store open?",why:"'The store' es singular → Is"},
    {sentence:"He is a good teacher.",question:"Is he a good teacher?",why:"'He' es 3ra persona singular → Is"},
    {sentence:"The coffee is hot.",question:"Is the coffee hot?",why:"'The coffee' es singular → Is"},
    {sentence:"She is nervous about the exam.",question:"Is she nervous about the exam?",why:"'She' es singular → Is"},
    {sentence:"The movie is interesting.",question:"Is the movie interesting?",why:"'The movie' es singular → Is"},
    {sentence:"He is at home right now.",question:"Is he at home right now?",why:"'He' es 3ra persona singular → Is"},
    {sentence:"The door is locked.",question:"Is the door locked?",why:"'The door' es singular → Is"},
    {sentence:"She is happy with her job.",question:"Is she happy with her job?",why:"'She' es 3ra persona singular → Is"},
    {sentence:"The meeting is at noon.",question:"Is the meeting at noon?",why:"'The meeting' es singular → Is"},
    {sentence:"He is the new manager.",question:"Is he the new manager?",why:"'He' es 3ra persona singular → Is"},
    {sentence:"The bus is late.",question:"Is the bus late?",why:"'The bus' es singular → Is"},
    {sentence:"She is wearing a red coat.",question:"Is she wearing a red coat?",why:"'She' es 3ra persona singular → Is"},
    {sentence:"The child is playing outside.",question:"Is the child playing outside?",why:"'The child' es singular → Is"},
    {sentence:"He is on the phone.",question:"Is he on the phone?",why:"'He' es 3ra persona singular → Is"},
    {sentence:"The food is ready.",question:"Is the food ready?",why:"'The food' es singular → Is"},
    {sentence:"She is taller than her sister.",question:"Is she taller than her sister?",why:"'She' es 3ra persona singular → Is"},
    {sentence:"The package is heavy.",question:"Is the package heavy?",why:"'The package' es singular → Is"},
    {sentence:"He is studying medicine.",question:"Is he studying medicine?",why:"'He' es 3ra persona singular → Is"},
    {sentence:"The airport is far from here.",question:"Is the airport far from here?",why:"'The airport' es singular → Is"},
    {sentence:"She is the team leader.",question:"Is she the team leader?",why:"'She' es 3ra persona singular → Is"},
    {sentence:"The price is too high.",question:"Is the price too high?",why:"'The price' es singular → Is"},
    {sentence:"He is sleeping right now.",question:"Is he sleeping right now?",why:"'He' es 3ra persona singular → Is"},
    {sentence:"The exam is difficult.",question:"Is the exam difficult?",why:"'The exam' es singular → Is"},
    {sentence:"She is interested in art.",question:"Is she interested in art?",why:"'She' es 3ra persona singular → Is"},
  ],
  are: [
    {sentence:"They are friends from college.",question:"Are they friends from college?",why:"'They' es plural, verbo 'to be' presente → Are + sujeto"},
    {sentence:"You are very kind.",question:"Are you very kind?",why:"'You' usa Are con 'to be' → Are + sujeto"},
    {sentence:"The books are on the shelf.",question:"Are the books on the shelf?",why:"'The books' es plural → Are + sujeto"},
    {sentence:"We are ready to start.",question:"Are we ready to start?",why:"'We' usa Are → Are + sujeto"},
    {sentence:"The students are tired.",question:"Are the students tired?",why:"'The students' es plural → Are"},
    {sentence:"They are coming to the party.",question:"Are they coming to the party?",why:"'They' es plural → Are"},
    {sentence:"You are the best player.",question:"Are you the best player?",why:"'You' usa Are → Are"},
    {sentence:"The kids are in the garden.",question:"Are the kids in the garden?",why:"'The kids' es plural → Are"},
    {sentence:"We are late for class.",question:"Are we late for class?",why:"'We' usa Are → Are"},
    {sentence:"They are watching TV.",question:"Are they watching TV?",why:"'They' es plural → Are"},
    {sentence:"The results are positive.",question:"Are the results positive?",why:"'The results' es plural → Are"},
    {sentence:"You are interested in this job.",question:"Are you interested in this job?",why:"'You' usa Are → Are"},
    {sentence:"The dogs are loud.",question:"Are the dogs loud?",why:"'The dogs' es plural → Are"},
    {sentence:"We are going to the beach.",question:"Are we going to the beach?",why:"'We' usa Are → Are"},
    {sentence:"They are from Mexico.",question:"Are they from Mexico?",why:"'They' es plural → Are"},
    {sentence:"The offices are closed today.",question:"Are the offices closed today?",why:"'The offices' es plural → Are"},
    {sentence:"You are working on a project.",question:"Are you working on a project?",why:"'You' usa Are → Are"},
    {sentence:"The prices are very high.",question:"Are the prices very high?",why:"'The prices' es plural → Are"},
    {sentence:"We are happy with the decision.",question:"Are we happy with the decision?",why:"'We' usa Are → Are"},
    {sentence:"The children are sleeping.",question:"Are the children sleeping?",why:"'The children' es plural → Are"},
    {sentence:"They are available tomorrow.",question:"Are they available tomorrow?",why:"'They' es plural → Are"},
    {sentence:"You are good at cooking.",question:"Are you good at cooking?",why:"'You' usa Are → Are"},
    {sentence:"The windows are open.",question:"Are the windows open?",why:"'The windows' es plural → Are"},
    {sentence:"We are planning a trip.",question:"Are we planning a trip?",why:"'We' usa Are → Are"},
    {sentence:"The trees are very tall.",question:"Are the trees very tall?",why:"'The trees' es plural → Are"},
    {sentence:"They are both lawyers.",question:"Are they both lawyers?",why:"'They' es plural → Are"},
    {sentence:"You are in the right place.",question:"Are you in the right place?",why:"'You' usa Are → Are"},
    {sentence:"The stores are open on Sunday.",question:"Are the stores open on Sunday?",why:"'The stores' es plural → Are"},
    {sentence:"We are neighbors.",question:"Are we neighbors?",why:"'We' usa Are → Are"},
    {sentence:"The answers are correct.",question:"Are the answers correct?",why:"'The answers' es plural → Are"},
  ],
  what: [
    {sentence:"She is reading something.",question:"What is she reading?",why:"Preguntamos por una cosa/objeto → What + verbo auxiliar + sujeto"},
    {sentence:"He wants something for dinner.",question:"What does he want for dinner?",why:"Preguntamos por una cosa → What + does (3ra sing.) + sujeto + verbo base"},
    {sentence:"They are doing something.",question:"What are they doing?",why:"Preguntamos por una acción → What + are + sujeto"},
    {sentence:"She bought something yesterday.",question:"What did she buy yesterday?",why:"Preguntamos por un objeto en pasado → What + did + sujeto + verbo base"},
    {sentence:"He is thinking about something.",question:"What is he thinking about?",why:"Preguntamos por una cosa → What + is + sujeto"},
    {sentence:"Maria cooks something on Sundays.",question:"What does Maria cook on Sundays?",why:"Preguntamos por la comida (cosa) → What + does + sujeto + verbo base"},
    {sentence:"The teacher explained something.",question:"What did the teacher explain?",why:"Preguntamos por el tema → What + did + sujeto + verbo base"},
    {sentence:"She said something important.",question:"What did she say?",why:"Preguntamos por las palabras → What + did + sujeto + verbo base"},
    {sentence:"He is going to do something.",question:"What is he going to do?",why:"Preguntamos por la acción futura → What + is + sujeto"},
    {sentence:"Something happened last night.",question:"What happened last night?",why:"'What' es el sujeto → What + verbo (sin auxiliar)"},
    {sentence:"She needs something from the store.",question:"What does she need from the store?",why:"Preguntamos por la cosa → What + does (3ra sing.) + sujeto + verbo base"},
    {sentence:"They discussed something in the meeting.",question:"What did they discuss in the meeting?",why:"Preguntamos por el tema → What + did + sujeto + verbo base"},
    {sentence:"He studies something at university.",question:"What does he study at university?",why:"Preguntamos por la materia → What + does (3ra sing.) + sujeto + verbo base"},
    {sentence:"The news report says something.",question:"What does the news report say?",why:"Preguntamos por el contenido → What + does + sujeto + verbo base"},
    {sentence:"She is wearing something red.",question:"What is she wearing?",why:"Preguntamos por la ropa → What + is + sujeto"},
    {sentence:"He found something interesting.",question:"What did he find?",why:"Preguntamos por el objeto → What + did + sujeto + verbo base"},
    {sentence:"They are building something.",question:"What are they building?",why:"Preguntamos por la construcción → What + are + sujeto"},
    {sentence:"She wrote something in her diary.",question:"What did she write in her diary?",why:"Preguntamos por el contenido → What + did + sujeto + verbo base"},
    {sentence:"He is eating something.",question:"What is he eating?",why:"Preguntamos por la comida → What + is + sujeto"},
    {sentence:"They are selling something new.",question:"What are they selling?",why:"Preguntamos por el producto → What + are + sujeto"},
    {sentence:"Something broke in the kitchen.",question:"What broke in the kitchen?",why:"'What' es el sujeto → What + verbo (sin auxiliar)"},
    {sentence:"She is learning something new.",question:"What is she learning?",why:"Preguntamos por el tema → What + is + sujeto"},
    {sentence:"He bought something expensive.",question:"What did he buy?",why:"Preguntamos por el objeto → What + did + sujeto + verbo base"},
    {sentence:"They are planning something.",question:"What are they planning?",why:"Preguntamos por el plan → What + are + sujeto"},
    {sentence:"She told him something.",question:"What did she tell him?",why:"Preguntamos por el mensaje → What + did + sujeto + verbo base"},
    {sentence:"He does something every morning.",question:"What does he do every morning?",why:"Preguntamos por la rutina → What + does (3ra sing.) + sujeto + verbo base"},
    {sentence:"They found something in the box.",question:"What did they find in the box?",why:"Preguntamos por el contenido → What + did + sujeto + verbo base"},
    {sentence:"She is drawing something.",question:"What is she drawing?",why:"Preguntamos por el dibujo → What + is + sujeto"},
    {sentence:"He gave her something.",question:"What did he give her?",why:"Preguntamos por el regalo/objeto → What + did + sujeto + verbo base"},
    {sentence:"Something is making noise.",question:"What is making noise?",why:"'What' es el sujeto → What + verbo (sin auxiliar)"},
  ],
  where: [
    {sentence:"She lives somewhere in the city.",question:"Where does she live?",why:"Preguntamos por el lugar → Where + does (3ra sing.) + sujeto + verbo base"},
    {sentence:"He works somewhere downtown.",question:"Where does he work?",why:"Preguntamos por el lugar → Where + does + sujeto + verbo base"},
    {sentence:"They went somewhere last weekend.",question:"Where did they go last weekend?",why:"Preguntamos por el destino en pasado → Where + did + sujeto + verbo base"},
    {sentence:"She is going somewhere tonight.",question:"Where is she going tonight?",why:"Preguntamos por el destino → Where + is + sujeto"},
    {sentence:"The keys are somewhere in the house.",question:"Where are the keys?",why:"Preguntamos por la ubicación → Where + are + sujeto"},
    {sentence:"He studied somewhere in Europe.",question:"Where did he study?",why:"Preguntamos por el lugar en pasado → Where + did + sujeto + verbo base"},
    {sentence:"The restaurant is somewhere on Main Street.",question:"Where is the restaurant?",why:"Preguntamos por la ubicación → Where + is + sujeto"},
    {sentence:"They are meeting somewhere.",question:"Where are they meeting?",why:"Preguntamos por el lugar → Where + are + sujeto"},
    {sentence:"She bought her dress somewhere.",question:"Where did she buy her dress?",why:"Preguntamos por la tienda → Where + did + sujeto + verbo base"},
    {sentence:"He parked his car somewhere.",question:"Where did he park his car?",why:"Preguntamos por el lugar → Where + did + sujeto + verbo base"},
    {sentence:"The meeting is somewhere in the building.",question:"Where is the meeting?",why:"Preguntamos por la ubicación → Where + is + sujeto"},
    {sentence:"They live somewhere in the suburbs.",question:"Where do they live?",why:"Preguntamos por el lugar → Where + do (plural) + sujeto + verbo base"},
    {sentence:"She was born somewhere in Europe.",question:"Where was she born?",why:"Preguntamos por el lugar de nacimiento → Where + was + sujeto"},
    {sentence:"He put the report somewhere.",question:"Where did he put the report?",why:"Preguntamos por el lugar → Where + did + sujeto + verbo base"},
    {sentence:"The children are playing somewhere.",question:"Where are the children playing?",why:"Preguntamos por el lugar → Where + are + sujeto"},
    {sentence:"She is from somewhere in Asia.",question:"Where is she from?",why:"Preguntamos por el origen → Where + is + sujeto + from"},
    {sentence:"They traveled somewhere warm.",question:"Where did they travel?",why:"Preguntamos por el destino → Where + did + sujeto + verbo base"},
    {sentence:"He hid the money somewhere.",question:"Where did he hide the money?",why:"Preguntamos por el escondite → Where + did + sujeto + verbo base"},
    {sentence:"The airport is somewhere outside the city.",question:"Where is the airport?",why:"Preguntamos por la ubicación → Where + is + sujeto"},
    {sentence:"She went for a walk somewhere.",question:"Where did she go for a walk?",why:"Preguntamos por el lugar → Where + did + sujeto + verbo base"},
    {sentence:"They are going on vacation somewhere.",question:"Where are they going on vacation?",why:"Preguntamos por el destino → Where + are + sujeto"},
    {sentence:"He grew up somewhere in the north.",question:"Where did he grow up?",why:"Preguntamos por el lugar → Where + did + sujeto + verbo base"},
    {sentence:"The documents are somewhere in the office.",question:"Where are the documents?",why:"Preguntamos por la ubicación → Where + are + sujeto"},
    {sentence:"She studied abroad somewhere.",question:"Where did she study abroad?",why:"Preguntamos por el lugar → Where + did + sujeto + verbo base"},
    {sentence:"He is going on a trip somewhere.",question:"Where is he going on a trip?",why:"Preguntamos por el destino → Where + is + sujeto"},
    {sentence:"They found the treasure somewhere.",question:"Where did they find the treasure?",why:"Preguntamos por el lugar → Where + did + sujeto + verbo base"},
    {sentence:"She keeps her diary somewhere.",question:"Where does she keep her diary?",why:"Preguntamos por el lugar → Where + does (3ra sing.) + sujeto + verbo base"},
    {sentence:"The school is somewhere nearby.",question:"Where is the school?",why:"Preguntamos por la ubicación → Where + is + sujeto"},
    {sentence:"He moved somewhere quieter.",question:"Where did he move?",why:"Preguntamos por el lugar → Where + did + sujeto + verbo base"},
    {sentence:"They are staying somewhere comfortable.",question:"Where are they staying?",why:"Preguntamos por el alojamiento → Where + are + sujeto"},
  ],
  who: [
    {sentence:"Someone called you this morning.",question:"Who called you this morning?",why:"Preguntamos por la persona que hizo la acción → Who + verbo (Who es el sujeto, no se usa auxiliar)"},
    {sentence:"Someone is at the door.",question:"Who is at the door?",why:"Preguntamos por la persona → Who + is (verbo to be)"},
    {sentence:"Someone fixed the computer.",question:"Who fixed the computer?",why:"Who es el sujeto → Who + verbo en pasado (sin did)"},
    {sentence:"Someone will help you.",question:"Who will help you?",why:"Who es el sujeto → Who + will + verbo base"},
    {sentence:"She is talking to someone.",question:"Who is she talking to?",why:"Preguntamos por la persona (objeto) → Who + is + sujeto + verbo + to"},
    {sentence:"He works with someone interesting.",question:"Who does he work with?",why:"Preguntamos por el compañero → Who + does + sujeto + verbo base + with"},
    {sentence:"Someone broke the window.",question:"Who broke the window?",why:"Who es el sujeto → Who + verbo en pasado (sin did)"},
    {sentence:"They invited someone to the party.",question:"Who did they invite to the party?",why:"Preguntamos por el invitado (objeto) → Who + did + sujeto + verbo base"},
    {sentence:"Someone knows the answer.",question:"Who knows the answer?",why:"Who es el sujeto → Who + verbo (sin auxiliar)"},
    {sentence:"She married someone from Spain.",question:"Who did she marry?",why:"Preguntamos por la persona (objeto) → Who + did + sujeto + verbo base"},
    {sentence:"Someone teaches the class.",question:"Who teaches the class?",why:"Who es el sujeto → Who + verbo (sin auxiliar)"},
    {sentence:"He called someone last night.",question:"Who did he call last night?",why:"Preguntamos por el destinatario → Who + did + sujeto + verbo base"},
    {sentence:"Someone left this note.",question:"Who left this note?",why:"Who es el sujeto → Who + verbo en pasado (sin did)"},
    {sentence:"She is looking for someone.",question:"Who is she looking for?",why:"Preguntamos por la persona → Who + is + sujeto"},
    {sentence:"Someone helped him finish the project.",question:"Who helped him finish the project?",why:"Who es el sujeto → Who + verbo en pasado (sin did)"},
    {sentence:"They met someone important.",question:"Who did they meet?",why:"Preguntamos por la persona (objeto) → Who + did + sujeto + verbo base"},
    {sentence:"Someone is singing upstairs.",question:"Who is singing upstairs?",why:"Who es el sujeto → Who + is + verbo-ing"},
    {sentence:"He spoke to someone at the bank.",question:"Who did he speak to at the bank?",why:"Preguntamos por la persona (objeto) → Who + did + sujeto + verbo base"},
    {sentence:"Someone found my wallet.",question:"Who found my wallet?",why:"Who es el sujeto → Who + verbo en pasado (sin did)"},
    {sentence:"She is waiting for someone.",question:"Who is she waiting for?",why:"Preguntamos por la persona → Who + is + sujeto"},
    {sentence:"Someone recommended this restaurant.",question:"Who recommended this restaurant?",why:"Who es el sujeto → Who + verbo en pasado (sin did)"},
    {sentence:"They chose someone as leader.",question:"Who did they choose as leader?",why:"Preguntamos por la persona elegida → Who + did + sujeto + verbo base"},
    {sentence:"Someone designed this logo.",question:"Who designed this logo?",why:"Who es el sujeto → Who + verbo en pasado (sin did)"},
    {sentence:"She talked to someone after class.",question:"Who did she talk to after class?",why:"Preguntamos por la persona (objeto) → Who + did + sujeto + verbo base"},
    {sentence:"Someone is responsible for this.",question:"Who is responsible for this?",why:"Who es el sujeto → Who + is + adjetivo"},
    {sentence:"He told someone the secret.",question:"Who did he tell the secret?",why:"Preguntamos por la persona → Who + did + sujeto + verbo base"},
    {sentence:"Someone won the competition.",question:"Who won the competition?",why:"Who es el sujeto → Who + verbo en pasado (sin did)"},
    {sentence:"They hired someone new.",question:"Who did they hire?",why:"Preguntamos por el contratado → Who + did + sujeto + verbo base"},
    {sentence:"Someone is knocking.",question:"Who is knocking?",why:"Who es el sujeto → Who + is + verbo-ing"},
    {sentence:"She is dating someone from work.",question:"Who is she dating?",why:"Preguntamos por la persona → Who + is + sujeto"},
  ],
  which: [
    {sentence:"She chose one of the options.",question:"Which option did she choose?",why:"'Which' se usa cuando hay opciones limitadas/específicas + sustantivo → Which + noun + did + sujeto + verbo base"},
    {sentence:"He prefers one of the two cars.",question:"Which car does he prefer?",why:"Hay opciones definidas → Which + noun + does + sujeto + verbo base"},
    {sentence:"They took one of the buses.",question:"Which bus did they take?",why:"Opciones específicas → Which + noun + did + sujeto + verbo base"},
    {sentence:"She is reading one of the books.",question:"Which book is she reading?",why:"Opciones definidas → Which + noun + is + sujeto + verbo-ing"},
    {sentence:"He picked one of the colors.",question:"Which color did he pick?",why:"Opciones limitadas → Which + noun + did + sujeto + verbo base"},
    {sentence:"They ordered one of the dishes.",question:"Which dish did they order?",why:"Hay un menú definido → Which + noun + did + sujeto + verbo base"},
    {sentence:"She will attend one of the events.",question:"Which event will she attend?",why:"Opciones conocidas → Which + noun + will + sujeto + verbo base"},
    {sentence:"He uses one of these methods.",question:"Which method does he use?",why:"Opciones específicas → Which + noun + does + sujeto + verbo base"},
    {sentence:"They live in one of those buildings.",question:"Which building do they live in?",why:"Opciones visibles → Which + noun + do + sujeto + verbo base"},
    {sentence:"She signed one of the forms.",question:"Which form did she sign?",why:"Hay formularios específicos → Which + noun + did + sujeto + verbo base"},
    {sentence:"He chose one of the candidates.",question:"Which candidate did he choose?",why:"Opciones limitadas → Which + noun + did + sujeto + verbo base"},
    {sentence:"They are going to one of the branches.",question:"Which branch are they going to?",why:"Sucursales definidas → Which + noun + are + sujeto + verbo-ing"},
    {sentence:"She bought one of the jackets.",question:"Which jacket did she buy?",why:"Opciones de la tienda → Which + noun + did + sujeto + verbo base"},
    {sentence:"He answered one of the questions.",question:"Which question did he answer?",why:"Preguntas específicas → Which + noun + did + sujeto + verbo base"},
    {sentence:"They chose one of the routes.",question:"Which route did they choose?",why:"Rutas definidas → Which + noun + did + sujeto + verbo base"},
    {sentence:"She is applying to one of the universities.",question:"Which university is she applying to?",why:"Lista de universidades → Which + noun + is + sujeto + verbo-ing"},
    {sentence:"He selected one of the plans.",question:"Which plan did he select?",why:"Planes específicos → Which + noun + did + sujeto + verbo base"},
    {sentence:"They prefer one of the teams.",question:"Which team do they prefer?",why:"Equipos conocidos → Which + noun + do + sujeto + verbo base"},
    {sentence:"She is wearing one of her scarves.",question:"Which scarf is she wearing?",why:"Bufandas definidas → Which + noun + is + sujeto + verbo-ing"},
    {sentence:"He fixed one of the machines.",question:"Which machine did he fix?",why:"Máquinas específicas → Which + noun + did + sujeto + verbo base"},
    {sentence:"They are using one of the meeting rooms.",question:"Which meeting room are they using?",why:"Salas definidas → Which + noun + are + sujeto + verbo-ing"},
    {sentence:"She passed one of the tests.",question:"Which test did she pass?",why:"Exámenes específicos → Which + noun + did + sujeto + verbo base"},
    {sentence:"He is driving one of the company cars.",question:"Which company car is he driving?",why:"Autos definidos → Which + noun + is + sujeto + verbo-ing"},
    {sentence:"They chose one of the suppliers.",question:"Which supplier did they choose?",why:"Proveedores conocidos → Which + noun + did + sujeto + verbo base"},
    {sentence:"She uses one of these apps.",question:"Which app does she use?",why:"Apps específicas → Which + noun + does + sujeto + verbo base"},
    {sentence:"He took one of the available seats.",question:"Which seat did he take?",why:"Asientos específicos → Which + noun + did + sujeto + verbo base"},
    {sentence:"They read one of the reports.",question:"Which report did they read?",why:"Reportes definidos → Which + noun + did + sujeto + verbo base"},
    {sentence:"She chose one of the doctors.",question:"Which doctor did she choose?",why:"Doctores específicos → Which + noun + did + sujeto + verbo base"},
    {sentence:"He took one of the exits.",question:"Which exit did he take?",why:"Salidas definidas → Which + noun + did + sujeto + verbo base"},
    {sentence:"They picked one of the available dates.",question:"Which date did they pick?",why:"Fechas limitadas → Which + noun + did + sujeto + verbo base"},
  ],
  how: [
    {sentence:"She commutes to work in some way.",question:"How does she commute to work?",why:"Preguntamos por la manera/forma → How + does (3ra sing.) + sujeto + verbo base"},
    {sentence:"He fixed the problem somehow.",question:"How did he fix the problem?",why:"Preguntamos por el método → How + did + sujeto + verbo base"},
    {sentence:"They communicate in some way.",question:"How do they communicate?",why:"Preguntamos por la manera → How + do (plural) + sujeto + verbo base"},
    {sentence:"She learned English in some way.",question:"How did she learn English?",why:"Preguntamos por el método → How + did + sujeto + verbo base"},
    {sentence:"He makes his coffee in some way.",question:"How does he make his coffee?",why:"Preguntamos por la preparación → How + does + sujeto + verbo base"},
    {sentence:"The system works in some way.",question:"How does the system work?",why:"Preguntamos por el funcionamiento → How + does + sujeto + verbo base"},
    {sentence:"She feels in some way about this.",question:"How does she feel about this?",why:"Preguntamos por el estado emocional → How + does + sujeto + verbo base"},
    {sentence:"He responded in some way.",question:"How did he respond?",why:"Preguntamos por la reacción → How + did + sujeto + verbo base"},
    {sentence:"They solved the problem in some way.",question:"How did they solve the problem?",why:"Preguntamos por el método → How + did + sujeto + verbo base"},
    {sentence:"She dresses in some style.",question:"How does she dress?",why:"Preguntamos por el estilo → How + does + sujeto + verbo base"},
    {sentence:"He explained it in some way.",question:"How did he explain it?",why:"Preguntamos por la explicación → How + did + sujeto + verbo base"},
    {sentence:"They train in some way.",question:"How do they train?",why:"Preguntamos por el método → How + do + sujeto + verbo base"},
    {sentence:"The app works in some way.",question:"How does the app work?",why:"Preguntamos por el funcionamiento → How + does + sujeto + verbo base"},
    {sentence:"She handled the situation somehow.",question:"How did she handle the situation?",why:"Preguntamos por la gestión → How + did + sujeto + verbo base"},
    {sentence:"He reacted in some way to the news.",question:"How did he react to the news?",why:"Preguntamos por la reacción → How + did + sujeto + verbo base"},
    {sentence:"They pay their employees in some way.",question:"How do they pay their employees?",why:"Preguntamos por el método → How + do + sujeto + verbo base"},
    {sentence:"She prepares for exams in some way.",question:"How does she prepare for exams?",why:"Preguntamos por el método → How + does + sujeto + verbo base"},
    {sentence:"He found out the news somehow.",question:"How did he find out the news?",why:"Preguntamos por el medio → How + did + sujeto + verbo base"},
    {sentence:"They celebrated in some way.",question:"How did they celebrate?",why:"Preguntamos por la celebración → How + did + sujeto + verbo base"},
    {sentence:"She manages the team somehow.",question:"How does she manage the team?",why:"Preguntamos por el estilo de gestión → How + does + sujeto + verbo base"},
    {sentence:"He saved money somehow.",question:"How did he save money?",why:"Preguntamos por el método → How + did + sujeto + verbo base"},
    {sentence:"They chose the winner somehow.",question:"How did they choose the winner?",why:"Preguntamos por el proceso → How + did + sujeto + verbo base"},
    {sentence:"She writes her reports in some way.",question:"How does she write her reports?",why:"Preguntamos por el proceso → How + does + sujeto + verbo base"},
    {sentence:"He deals with stress somehow.",question:"How does he deal with stress?",why:"Preguntamos por el método → How + does + sujeto + verbo base"},
    {sentence:"They exercise in some way.",question:"How do they exercise?",why:"Preguntamos por la rutina → How + do + sujeto + verbo base"},
    {sentence:"She decorated her room in some way.",question:"How did she decorate her room?",why:"Preguntamos por el estilo → How + did + sujeto + verbo base"},
    {sentence:"He recovered from the injury somehow.",question:"How did he recover from the injury?",why:"Preguntamos por el proceso → How + did + sujeto + verbo base"},
    {sentence:"They organize their files in some way.",question:"How do they organize their files?",why:"Preguntamos por el método → How + do + sujeto + verbo base"},
    {sentence:"She calms down somehow.",question:"How does she calm down?",why:"Preguntamos por la técnica → How + does + sujeto + verbo base"},
    {sentence:"He persuaded them somehow.",question:"How did he persuade them?",why:"Preguntamos por el método → How + did + sujeto + verbo base"},
  ],
  how_many: [
    {sentence:"She has some siblings.",question:"How many siblings does she have?",why:"Preguntamos por cantidad de algo contable → How many + noun (plural) + does/do/did + sujeto + verbo base"},
    {sentence:"They bought some tickets.",question:"How many tickets did they buy?",why:"'Tickets' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"He has some books on the shelf.",question:"How many books does he have on the shelf?",why:"'Books' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"She ate some cookies.",question:"How many cookies did she eat?",why:"'Cookies' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"There are some students in the class.",question:"How many students are there in the class?",why:"'Students' es contable → How many + noun + are there"},
    {sentence:"He has some years of experience.",question:"How many years of experience does he have?",why:"'Years' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"They sent some emails.",question:"How many emails did they send?",why:"'Emails' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"She has some languages she speaks.",question:"How many languages does she speak?",why:"'Languages' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"He took some days off.",question:"How many days off did he take?",why:"'Days' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"There are some rooms in the hotel.",question:"How many rooms are there in the hotel?",why:"'Rooms' es contable → How many + noun + are there"},
    {sentence:"They invited some guests.",question:"How many guests did they invite?",why:"'Guests' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"She has some children.",question:"How many children does she have?",why:"'Children' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"He answered some questions correctly.",question:"How many questions did he answer correctly?",why:"'Questions' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"They have some offices worldwide.",question:"How many offices do they have worldwide?",why:"'Offices' es contable → How many + noun + do + sujeto + verbo base"},
    {sentence:"She visited some countries.",question:"How many countries did she visit?",why:"'Countries' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"He has some meetings today.",question:"How many meetings does he have today?",why:"'Meetings' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"They produced some units.",question:"How many units did they produce?",why:"'Units' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"She reads some books per month.",question:"How many books does she read per month?",why:"'Books' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"He has some cars in his collection.",question:"How many cars does he have in his collection?",why:"'Cars' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"There are some people in line.",question:"How many people are there in line?",why:"'People' es contable → How many + noun + are there"},
    {sentence:"They hired some employees last year.",question:"How many employees did they hire last year?",why:"'Employees' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"She took some photos at the event.",question:"How many photos did she take at the event?",why:"'Photos' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"He has some pets.",question:"How many pets does he have?",why:"'Pets' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"They completed some projects this year.",question:"How many projects did they complete this year?",why:"'Projects' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"She has some apps on her phone.",question:"How many apps does she have on her phone?",why:"'Apps' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"He ate some slices of pizza.",question:"How many slices of pizza did he eat?",why:"'Slices' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"They have some branches in the country.",question:"How many branches do they have in the country?",why:"'Branches' es contable → How many + noun + do + sujeto + verbo base"},
    {sentence:"She has some exams this week.",question:"How many exams does she have this week?",why:"'Exams' es contable → How many + noun + does + sujeto + verbo base"},
    {sentence:"He called some clients yesterday.",question:"How many clients did he call yesterday?",why:"'Clients' es contable → How many + noun + did + sujeto + verbo base"},
    {sentence:"They made some mistakes.",question:"How many mistakes did they make?",why:"'Mistakes' es contable → How many + noun + did + sujeto + verbo base"},
  ],
  how_much: [
    {sentence:"She spent some money on shoes.",question:"How much money did she spend on shoes?",why:"'Money' es incontable → How much + noun (singular) + did + sujeto + verbo base"},
    {sentence:"He drinks some coffee every day.",question:"How much coffee does he drink every day?",why:"'Coffee' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"They paid some money for the car.",question:"How much did they pay for the car?",why:"'Money' incontable → How much + did + sujeto + verbo base"},
    {sentence:"She needs some time to finish.",question:"How much time does she need to finish?",why:"'Time' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"He earns some money per month.",question:"How much does he earn per month?",why:"Cantidad de dinero incontable → How much + does + sujeto + verbo base"},
    {sentence:"The shirt costs some amount.",question:"How much does the shirt cost?",why:"Precio, dinero incontable → How much + does + sujeto + verbo base"},
    {sentence:"She added some sugar to the recipe.",question:"How much sugar did she add?",why:"'Sugar' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"He has some experience in marketing.",question:"How much experience does he have in marketing?",why:"'Experience' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"They spent some time on the project.",question:"How much time did they spend on the project?",why:"'Time' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"She uses some water every day.",question:"How much water does she use every day?",why:"'Water' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"He ate some bread at breakfast.",question:"How much bread did he eat at breakfast?",why:"'Bread' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"The apartment costs some rent.",question:"How much is the rent for the apartment?",why:"Precio, 'rent' incontable → How much + is + sujeto"},
    {sentence:"They have some information about it.",question:"How much information do they have about it?",why:"'Information' es incontable → How much + noun + do + sujeto + verbo base"},
    {sentence:"She put some effort into it.",question:"How much effort did she put into it?",why:"'Effort' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"He drank some water after the race.",question:"How much water did he drink after the race?",why:"'Water' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"They invested some money in the startup.",question:"How much did they invest in the startup?",why:"Monto de dinero incontable → How much + did + sujeto + verbo base"},
    {sentence:"She needs some help.",question:"How much help does she need?",why:"'Help' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"He spent some time studying.",question:"How much time did he spend studying?",why:"'Time' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"They used some fuel on the trip.",question:"How much fuel did they use on the trip?",why:"'Fuel' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"She has some milk left.",question:"How much milk does she have left?",why:"'Milk' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"He owes some money.",question:"How much money does he owe?",why:"'Money' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"The project needs some funding.",question:"How much funding does the project need?",why:"'Funding' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"She added some salt.",question:"How much salt did she add?",why:"'Salt' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"He has some free time this week.",question:"How much free time does he have this week?",why:"'Free time' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"They wasted some energy.",question:"How much energy did they waste?",why:"'Energy' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"She drinks some juice in the morning.",question:"How much juice does she drink in the morning?",why:"'Juice' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"He has some knowledge of French.",question:"How much knowledge of French does he have?",why:"'Knowledge' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"They spent some time traveling.",question:"How much time did they spend traveling?",why:"'Time' es incontable → How much + noun + did + sujeto + verbo base"},
    {sentence:"She needs some space.",question:"How much space does she need?",why:"'Space' es incontable → How much + noun + does + sujeto + verbo base"},
    {sentence:"He ate some rice.",question:"How much rice did he eat?",why:"'Rice' es incontable → How much + noun + did + sujeto + verbo base"},
  ],
  was: [
    {sentence:"She was at the party last night.",question:"Was she at the party last night?",why:"'She' es singular, pasado de 'to be' → Was + sujeto"},
    {sentence:"He was tired after work.",question:"Was he tired after work?",why:"'He' es singular, pasado → Was + sujeto"},
    {sentence:"The food was delicious.",question:"Was the food delicious?",why:"'The food' es singular, pasado → Was + sujeto"},
    {sentence:"Maria was the best student.",question:"Was Maria the best student?",why:"'Maria' es singular, pasado → Was + sujeto"},
    {sentence:"The movie was interesting.",question:"Was the movie interesting?",why:"'The movie' es singular, pasado → Was + sujeto"},
    {sentence:"She was happy with the result.",question:"Was she happy with the result?",why:"'She' es singular, pasado → Was + sujeto"},
    {sentence:"The meeting was on Monday.",question:"Was the meeting on Monday?",why:"'The meeting' es singular, pasado → Was + sujeto"},
    {sentence:"He was the winner.",question:"Was he the winner?",why:"'He' es singular, pasado → Was + sujeto"},
    {sentence:"The trip was exhausting.",question:"Was the trip exhausting?",why:"'The trip' es singular, pasado → Was + sujeto"},
    {sentence:"She was nervous before the exam.",question:"Was she nervous before the exam?",why:"'She' es singular, pasado → Was + sujeto"},
    {sentence:"The price was too high.",question:"Was the price too high?",why:"'The price' es singular, pasado → Was + sujeto"},
    {sentence:"He was a famous musician.",question:"Was he a famous musician?",why:"'He' es singular, pasado → Was + sujeto"},
    {sentence:"The weather was cold.",question:"Was the weather cold?",why:"'The weather' es singular, pasado → Was + sujeto"},
    {sentence:"She was late for the meeting.",question:"Was she late for the meeting?",why:"'She' es singular, pasado → Was + sujeto"},
    {sentence:"The plan was a good idea.",question:"Was the plan a good idea?",why:"'The plan' es singular, pasado → Was + sujeto"},
    {sentence:"He was in charge of the project.",question:"Was he in charge of the project?",why:"'He' es singular, pasado → Was + sujeto"},
    {sentence:"The result was unexpected.",question:"Was the result unexpected?",why:"'The result' es singular, pasado → Was + sujeto"},
    {sentence:"She was angry about it.",question:"Was she angry about it?",why:"'She' es singular, pasado → Was + sujeto"},
    {sentence:"The book was on the table.",question:"Was the book on the table?",why:"'The book' es singular, pasado → Was + sujeto"},
    {sentence:"He was born in 1990.",question:"Was he born in 1990?",why:"'He' es singular, pasado → Was + sujeto"},
    {sentence:"The door was locked.",question:"Was the door locked?",why:"'The door' es singular, pasado → Was + sujeto"},
    {sentence:"She was the team captain.",question:"Was she the team captain?",why:"'She' es singular, pasado → Was + sujeto"},
    {sentence:"The conference was successful.",question:"Was the conference successful?",why:"'The conference' es singular, pasado → Was + sujeto"},
    {sentence:"He was absent yesterday.",question:"Was he absent yesterday?",why:"'He' es singular, pasado → Was + sujeto"},
    {sentence:"The restaurant was full.",question:"Was the restaurant full?",why:"'The restaurant' es singular, pasado → Was + sujeto"},
    {sentence:"She was responsible for the event.",question:"Was she responsible for the event?",why:"'She' es singular, pasado → Was + sujeto"},
    {sentence:"The information was correct.",question:"Was the information correct?",why:"'The information' es singular, pasado → Was + sujeto"},
    {sentence:"He was excited about the trip.",question:"Was he excited about the trip?",why:"'He' es singular, pasado → Was + sujeto"},
    {sentence:"The office was empty.",question:"Was the office empty?",why:"'The office' es singular, pasado → Was + sujeto"},
    {sentence:"She was ready on time.",question:"Was she ready on time?",why:"'She' es singular, pasado → Was + sujeto"},
  ],
  were: [
    {sentence:"They were at the concert last night.",question:"Were they at the concert last night?",why:"'They' es plural, pasado de 'to be' → Were + sujeto"},
    {sentence:"You were right about that.",question:"Were you right about that?",why:"'You' usa Were en pasado → Were + sujeto"},
    {sentence:"The students were ready for the test.",question:"Were the students ready for the test?",why:"'The students' es plural, pasado → Were + sujeto"},
    {sentence:"We were late for the flight.",question:"Were we late for the flight?",why:"'We' usa Were → Were + sujeto"},
    {sentence:"The results were positive.",question:"Were the results positive?",why:"'The results' es plural, pasado → Were + sujeto"},
    {sentence:"They were friends in college.",question:"Were they friends in college?",why:"'They' es plural, pasado → Were + sujeto"},
    {sentence:"You were the best player.",question:"Were you the best player?",why:"'You' usa Were → Were + sujeto"},
    {sentence:"The prices were reasonable.",question:"Were the prices reasonable?",why:"'The prices' es plural, pasado → Were + sujeto"},
    {sentence:"We were happy with the service.",question:"Were we happy with the service?",why:"'We' usa Were → Were + sujeto"},
    {sentence:"The offices were closed.",question:"Were the offices closed?",why:"'The offices' es plural, pasado → Were + sujeto"},
    {sentence:"They were excited about the news.",question:"Were they excited about the news?",why:"'They' es plural, pasado → Were + sujeto"},
    {sentence:"You were the first to arrive.",question:"Were you the first to arrive?",why:"'You' usa Were → Were + sujeto"},
    {sentence:"The kids were tired.",question:"Were the kids tired?",why:"'The kids' es plural, pasado → Were + sujeto"},
    {sentence:"We were wrong about it.",question:"Were we wrong about it?",why:"'We' usa Were → Were + sujeto"},
    {sentence:"The documents were ready.",question:"Were the documents ready?",why:"'The documents' es plural, pasado → Were + sujeto"},
    {sentence:"They were born in the same city.",question:"Were they born in the same city?",why:"'They' es plural, pasado → Were + sujeto"},
    {sentence:"You were available on Friday.",question:"Were you available on Friday?",why:"'You' usa Were → Were + sujeto"},
    {sentence:"The windows were open all night.",question:"Were the windows open all night?",why:"'The windows' es plural, pasado → Were + sujeto"},
    {sentence:"We were surprised by the decision.",question:"Were we surprised by the decision?",why:"'We' usa Were → Were + sujeto"},
    {sentence:"The flights were cancelled.",question:"Were the flights cancelled?",why:"'The flights' es plural, pasado → Were + sujeto"},
    {sentence:"They were in a meeting all morning.",question:"Were they in a meeting all morning?",why:"'They' es plural, pasado → Were + sujeto"},
    {sentence:"You were nervous during the interview.",question:"Were you nervous during the interview?",why:"'You' usa Were → Were + sujeto"},
    {sentence:"The answers were incorrect.",question:"Were the answers incorrect?",why:"'The answers' es plural, pasado → Were + sujeto"},
    {sentence:"We were responsible for the mistake.",question:"Were we responsible for the mistake?",why:"'We' usa Were → Were + sujeto"},
    {sentence:"The children were playing outside.",question:"Were the children playing outside?",why:"'The children' es plural, pasado → Were + sujeto"},
    {sentence:"They were satisfied with the results.",question:"Were they satisfied with the results?",why:"'They' es plural, pasado → Were + sujeto"},
    {sentence:"You were the last to leave.",question:"Were you the last to leave?",why:"'You' usa Were → Were + sujeto"},
    {sentence:"The emails were sent on time.",question:"Were the emails sent on time?",why:"'The emails' es plural, pasado → Were + sujeto"},
    {sentence:"We were given a second chance.",question:"Were we given a second chance?",why:"'We' usa Were → Were + sujeto"},
    {sentence:"The streets were empty.",question:"Were the streets empty?",why:"'The streets' es plural, pasado → Were + sujeto"},
  ],
  whom: [
    {sentence:"She was talking to someone formal.",question:"To whom was she talking?",why:"WHOM se usa como objeto formal de preposición → To whom + was/did + sujeto + verbo"},
    {sentence:"He sent the report to someone.",question:"To whom did he send the report?",why:"WHOM reemplaza al objeto de la preposición 'to' → To whom + did + sujeto + verbo base"},
    {sentence:"They addressed the letter to someone.",question:"To whom did they address the letter?",why:"WHOM es objeto formal → To whom + did + sujeto + verbo base"},
    {sentence:"She gave the award to someone.",question:"To whom did she give the award?",why:"WHOM como objeto indirecto formal → To whom + did + sujeto + verbo base"},
    {sentence:"He was speaking with someone important.",question:"With whom was he speaking?",why:"WHOM objeto de preposición 'with' → With whom + was + sujeto + verbo-ing"},
    {sentence:"They elected someone as president.",question:"Whom did they elect as president?",why:"WHOM es objeto directo formal → Whom + did + sujeto + verbo base"},
    {sentence:"She recommended someone for the job.",question:"Whom did she recommend for the job?",why:"WHOM objeto directo → Whom + did + sujeto + verbo base"},
    {sentence:"He consulted someone before deciding.",question:"Whom did he consult before deciding?",why:"WHOM objeto directo → Whom + did + sujeto + verbo base"},
    {sentence:"They hired someone with experience.",question:"Whom did they hire?",why:"WHOM objeto directo → Whom + did + sujeto + verbo base"},
    {sentence:"She married someone from abroad.",question:"Whom did she marry?",why:"WHOM objeto directo → Whom + did + sujeto + verbo base"},
    {sentence:"He informed someone about the change.",question:"Whom did he inform about the change?",why:"WHOM objeto directo → Whom + did + sujeto + verbo base"},
    {sentence:"They blamed someone for the mistake.",question:"Whom did they blame for the mistake?",why:"WHOM objeto directo → Whom + did + sujeto + verbo base"},
    {sentence:"She was interviewing someone.",question:"Whom was she interviewing?",why:"WHOM objeto de acción en progreso → Whom + was + sujeto + verbo-ing"},
    {sentence:"He was representing someone in court.",question:"Whom was he representing in court?",why:"WHOM objeto formal → Whom + was + sujeto + verbo-ing"},
    {sentence:"They contacted someone at the embassy.",question:"Whom did they contact at the embassy?",why:"WHOM objeto directo → Whom + did + sujeto + verbo base"},
    {sentence:"She was writing to someone overseas.",question:"To whom was she writing?",why:"WHOM con preposición 'to' → To whom + was + sujeto + verbo-ing"},
    {sentence:"He referred the client to someone.",question:"To whom did he refer the client?",why:"WHOM objeto de preposición → To whom + did + sujeto + verbo base"},
    {sentence:"They transferred the funds to someone.",question:"To whom did they transfer the funds?",why:"WHOM objeto de preposición formal → To whom + did + sujeto + verbo base"},
    {sentence:"She was reporting to someone new.",question:"To whom was she reporting?",why:"WHOM con preposición formal → To whom + was + sujeto + verbo-ing"},
    {sentence:"He dedicated the book to someone.",question:"To whom did he dedicate the book?",why:"WHOM objeto de preposición → To whom + did + sujeto + verbo base"},
    {sentence:"They awarded the prize to someone.",question:"To whom did they award the prize?",why:"WHOM objeto de preposición → To whom + did + sujeto + verbo base"},
    {sentence:"She complained to someone in charge.",question:"To whom did she complain?",why:"WHOM con preposición formal → To whom + did + sujeto + verbo base"},
    {sentence:"He was talking about someone specific.",question:"About whom was he talking?",why:"WHOM objeto de preposición 'about' → About whom + was + sujeto + verbo-ing"},
    {sentence:"They sent an invitation to someone.",question:"To whom did they send an invitation?",why:"WHOM objeto de preposición → To whom + did + sujeto + verbo base"},
    {sentence:"She was assigned to work with someone.",question:"With whom was she assigned to work?",why:"WHOM con preposición 'with' → With whom + was + sujeto + verbo"},
    {sentence:"He passed the message to someone.",question:"To whom did he pass the message?",why:"WHOM objeto de preposición → To whom + did + sujeto + verbo base"},
    {sentence:"They reported the incident to someone.",question:"To whom did they report the incident?",why:"WHOM objeto de preposición → To whom + did + sujeto + verbo base"},
    {sentence:"She was engaged to someone abroad.",question:"To whom was she engaged?",why:"WHOM objeto de preposición → To whom + was + sujeto + verbo"},
    {sentence:"He introduced her to someone important.",question:"To whom did he introduce her?",why:"WHOM objeto de preposición → To whom + did + sujeto + verbo base"},
    {sentence:"They gave access to someone authorized.",question:"To whom did they give access?",why:"WHOM objeto de preposición → To whom + did + sujeto + verbo base"},
  ],
  whose: [
    {sentence:"Someone's car is blocking the driveway.",question:"Whose car is blocking the driveway?",why:"WHOSE pregunta por posesión → Whose + noun + verbo auxiliar + sujeto"},
    {sentence:"Someone's phone was left on the table.",question:"Whose phone was left on the table?",why:"WHOSE + noun (cosa poseída) + was + sujeto"},
    {sentence:"Someone's idea was chosen.",question:"Whose idea was chosen?",why:"WHOSE + noun + was + verbo"},
    {sentence:"Someone's keys are on the counter.",question:"Whose keys are on the counter?",why:"WHOSE + noun + are + lugar"},
    {sentence:"Someone's report did not arrive.",question:"Whose report did not arrive?",why:"WHOSE + noun + did + verbo base"},
    {sentence:"Someone's signature is required.",question:"Whose signature is required?",why:"WHOSE + noun + is + verbo"},
    {sentence:"Someone's dog keeps barking.",question:"Whose dog keeps barking?",why:"WHOSE + noun + verbo (sujeto = whose + noun)"},
    {sentence:"Someone's bag was left at the office.",question:"Whose bag was left at the office?",why:"WHOSE + noun + was + verbo en pasado"},
    {sentence:"Someone's project won first place.",question:"Whose project won first place?",why:"WHOSE + noun actúa como sujeto + verbo en pasado"},
    {sentence:"Someone's jacket is on the chair.",question:"Whose jacket is on the chair?",why:"WHOSE + noun + is + lugar"},
    {sentence:"Someone's idea inspired the team.",question:"Whose idea inspired the team?",why:"WHOSE + noun como sujeto + verbo en pasado"},
    {sentence:"Someone's number did she call.",question:"Whose number did she call?",why:"WHOSE + noun + did + sujeto + verbo base"},
    {sentence:"Someone's turn is it to present.",question:"Whose turn is it to present?",why:"WHOSE + noun + is + it → pregunta de turno"},
    {sentence:"Someone's work did they review.",question:"Whose work did they review?",why:"WHOSE + noun + did + sujeto + verbo base"},
    {sentence:"Someone's permission do we need.",question:"Whose permission do we need?",why:"WHOSE + noun + do + sujeto + verbo base"},
    {sentence:"Someone's fault was the accident.",question:"Whose fault was the accident?",why:"WHOSE + noun + was + sujeto"},
    {sentence:"Someone's laptop did you borrow.",question:"Whose laptop did you borrow?",why:"WHOSE + noun + did + sujeto + verbo base"},
    {sentence:"Someone's birthday is today.",question:"Whose birthday is today?",why:"WHOSE + noun + is + tiempo"},
    {sentence:"Someone's idea are they following.",question:"Whose idea are they following?",why:"WHOSE + noun + are + sujeto + verbo-ing"},
    {sentence:"Someone's recommendation got her the job.",question:"Whose recommendation got her the job?",why:"WHOSE + noun como sujeto + verbo en pasado"},
    {sentence:"Someone's child was crying in the hall.",question:"Whose child was crying in the hall?",why:"WHOSE + noun + was + verbo-ing"},
    {sentence:"Someone's presentation was the best.",question:"Whose presentation was the best?",why:"WHOSE + noun + was + adjetivo"},
    {sentence:"Someone's account was hacked.",question:"Whose account was hacked?",why:"WHOSE + noun + was + participio"},
    {sentence:"Someone's idea did the boss approve.",question:"Whose idea did the boss approve?",why:"WHOSE + noun + did + sujeto + verbo base"},
    {sentence:"Someone's car did the police tow.",question:"Whose car did the police tow?",why:"WHOSE + noun + did + sujeto + verbo base"},
    {sentence:"Someone's voice do I hear.",question:"Whose voice do I hear?",why:"WHOSE + noun + do + sujeto + verbo base"},
    {sentence:"Someone's handwriting is on the note.",question:"Whose handwriting is on the note?",why:"WHOSE + noun + is + lugar"},
    {sentence:"Someone's version of events is correct.",question:"Whose version of events is correct?",why:"WHOSE + noun + is + adjetivo"},
    {sentence:"Someone's advice did she follow.",question:"Whose advice did she follow?",why:"WHOSE + noun + did + sujeto + verbo base"},
    {sentence:"Someone's desk is the messiest.",question:"Whose desk is the messiest?",why:"WHOSE + noun + is + superlativo"},
  ],
  when: [
    {sentence:"She arrived at some point.",question:"When did she arrive?",why:"Preguntamos por el tiempo/momento → When + did + sujeto + verbo base"},
    {sentence:"He will call at some time.",question:"When will he call?",why:"Preguntamos por el momento futuro → When + will + sujeto + verbo base"},
    {sentence:"The meeting starts at some time.",question:"When does the meeting start?",why:"Preguntamos por la hora → When + does + sujeto + verbo base"},
    {sentence:"They left at some point last night.",question:"When did they leave?",why:"Momento en pasado → When + did + sujeto + verbo base"},
    {sentence:"She will graduate at some point.",question:"When will she graduate?",why:"Momento futuro → When + will + sujeto + verbo base"},
    {sentence:"The package arrived at some time.",question:"When did the package arrive?",why:"Momento en pasado → When + did + sujeto + verbo base"},
    {sentence:"He usually exercises at some time.",question:"When does he usually exercise?",why:"Momento habitual → When + does + sujeto + verbo base"},
    {sentence:"The store opens at some time.",question:"When does the store open?",why:"Momento en presente → When + does + sujeto + verbo base"},
    {sentence:"They got married at some point.",question:"When did they get married?",why:"Momento en pasado → When + did + sujeto + verbo base"},
    {sentence:"She started her new job at some point.",question:"When did she start her new job?",why:"Momento en pasado → When + did + sujeto + verbo base"},
    {sentence:"The exam is at some time tomorrow.",question:"When is the exam?",why:"Momento con 'to be' → When + is + sujeto"},
    {sentence:"He finished the project at some point.",question:"When did he finish the project?",why:"Momento en pasado → When + did + sujeto + verbo base"},
    {sentence:"The next flight departs at some time.",question:"When does the next flight depart?",why:"Momento habitual/horario → When + does + sujeto + verbo base"},
    {sentence:"They will announce the results at some point.",question:"When will they announce the results?",why:"Momento futuro → When + will + sujeto + verbo base"},
    {sentence:"She is coming back at some time.",question:"When is she coming back?",why:"Momento en presente continuo → When + is + sujeto + verbo-ing"},
    {sentence:"The accident happened at some point.",question:"When did the accident happen?",why:"Momento en pasado → When + did + sujeto + verbo base"},
    {sentence:"He was born at some point in time.",question:"When was he born?",why:"Momento en pasado con 'to be' → When + was + sujeto + verbo"},
    {sentence:"The concert ends at some time.",question:"When does the concert end?",why:"Momento habitual → When + does + sujeto + verbo base"},
    {sentence:"They are moving to their new house at some point.",question:"When are they moving?",why:"Momento en presente continuo → When + are + sujeto + verbo-ing"},
    {sentence:"She submitted the form at some point.",question:"When did she submit the form?",why:"Momento en pasado → When + did + sujeto + verbo base"},
    {sentence:"The program starts at some time.",question:"When does the program start?",why:"Momento habitual → When + does + sujeto + verbo base"},
    {sentence:"He will be available at some point.",question:"When will he be available?",why:"Momento futuro → When + will + sujeto + verbo base"},
    {sentence:"The results were announced at some point.",question:"When were the results announced?",why:"Momento en pasado con 'to be' → When + were + sujeto + verbo"},
    {sentence:"She learned the news at some point.",question:"When did she learn the news?",why:"Momento en pasado → When + did + sujeto + verbo base"},
    {sentence:"The project is due at some time.",question:"When is the project due?",why:"Momento con 'to be' → When + is + sujeto"},
    {sentence:"They called at some point during the day.",question:"When did they call?",why:"Momento en pasado → When + did + sujeto + verbo base"},
    {sentence:"He is planning to visit at some point.",question:"When is he planning to visit?",why:"Momento en presente continuo → When + is + sujeto + verbo-ing"},
    {sentence:"The offices were opened at some point.",question:"When were the offices opened?",why:"Momento en pasado con 'to be' → When + were + sujeto + verbo"},
    {sentence:"She will be ready at some point.",question:"When will she be ready?",why:"Momento futuro → When + will + sujeto + verbo base"},
    {sentence:"The vote took place at some point.",question:"When did the vote take place?",why:"Momento en pasado → When + did + sujeto + verbo base"},
  ],
  why: [
    {sentence:"She left early for some reason.",question:"Why did she leave early?",why:"Preguntamos por la razón/motivo → Why + did + sujeto + verbo base"},
    {sentence:"He is upset for some reason.",question:"Why is he upset?",why:"Razón en presente → Why + is + sujeto + adjetivo"},
    {sentence:"They canceled the event for some reason.",question:"Why did they cancel the event?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
    {sentence:"She studies so hard for some reason.",question:"Why does she study so hard?",why:"Razón habitual → Why + does + sujeto + verbo base"},
    {sentence:"He didn't come to work for some reason.",question:"Why didn't he come to work?",why:"Razón negativa en pasado → Why + didn't + sujeto + verbo base"},
    {sentence:"The flight was delayed for some reason.",question:"Why was the flight delayed?",why:"Razón en pasado con 'to be' → Why + was + sujeto + verbo"},
    {sentence:"They are moving for some reason.",question:"Why are they moving?",why:"Razón en presente continuo → Why + are + sujeto + verbo-ing"},
    {sentence:"She doesn't eat meat for some reason.",question:"Why doesn't she eat meat?",why:"Razón negativa habitual → Why + doesn't + sujeto + verbo base"},
    {sentence:"He chose that option for some reason.",question:"Why did he choose that option?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
    {sentence:"The store is closed for some reason.",question:"Why is the store closed?",why:"Razón en presente con 'to be' → Why + is + sujeto + adjetivo"},
    {sentence:"They hired her for some reason.",question:"Why did they hire her?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
    {sentence:"She is crying for some reason.",question:"Why is she crying?",why:"Razón en presente continuo → Why + is + sujeto + verbo-ing"},
    {sentence:"He wants to quit for some reason.",question:"Why does he want to quit?",why:"Razón habitual → Why + does + sujeto + verbo base"},
    {sentence:"The project failed for some reason.",question:"Why did the project fail?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
    {sentence:"They are arguing for some reason.",question:"Why are they arguing?",why:"Razón en presente continuo → Why + are + sujeto + verbo-ing"},
    {sentence:"She refused the offer for some reason.",question:"Why did she refuse the offer?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
    {sentence:"He looks worried for some reason.",question:"Why does he look worried?",why:"Razón habitual/estado → Why + does + sujeto + verbo base"},
    {sentence:"The computer isn't working for some reason.",question:"Why isn't the computer working?",why:"Razón negativa presente → Why + isn't + sujeto + verbo-ing"},
    {sentence:"They didn't respond for some reason.",question:"Why didn't they respond?",why:"Razón negativa en pasado → Why + didn't + sujeto + verbo base"},
    {sentence:"She was absent yesterday for some reason.",question:"Why was she absent yesterday?",why:"Razón en pasado con 'to be' → Why + was + sujeto + adjetivo"},
    {sentence:"He gave up for some reason.",question:"Why did he give up?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
    {sentence:"The prices went up for some reason.",question:"Why did the prices go up?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
    {sentence:"She is smiling for some reason.",question:"Why is she smiling?",why:"Razón en presente continuo → Why + is + sujeto + verbo-ing"},
    {sentence:"They were late for some reason.",question:"Why were they late?",why:"Razón en pasado con 'to be' → Why + were + sujeto + adjetivo"},
    {sentence:"He doesn't like the plan for some reason.",question:"Why doesn't he like the plan?",why:"Razón negativa habitual → Why + doesn't + sujeto + verbo base"},
    {sentence:"She switched teams for some reason.",question:"Why did she switch teams?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
    {sentence:"The manager resigned for some reason.",question:"Why did the manager resign?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
    {sentence:"They don't trust him for some reason.",question:"Why don't they trust him?",why:"Razón negativa habitual → Why + don't + sujeto + verbo base"},
    {sentence:"She is working overtime for some reason.",question:"Why is she working overtime?",why:"Razón en presente continuo → Why + is + sujeto + verbo-ing"},
    {sentence:"He changed his mind for some reason.",question:"Why did he change his mind?",why:"Razón en pasado → Why + did + sujeto + verbo base"},
  ],
};
