// ─────────────────────────────────────────────────────────────────
// VERBS_EXTRA — verbos adicionales para el Diccionario de Verbos
// Este archivo se carga junto a index.html y se fusiona con VERBS,
// evitando duplicados automáticamente (ver script principal).
// Agrega aquí más verbos cuando quieras — mismo formato que index.html.
// ─────────────────────────────────────────────────────────────────
const VERBS_EXTRA = [

  // ─── IRREGULARES QUE FALTABAN ─────────────────────────────────
  { type: "irregular", base: "Shave", past: "Shaved", participle: "Shaved / Shaven", esPres: "Afeitar / Rasurar", esPast: "Afeitó / Rasuró", esPart: "Afeitado / Rasurado" },
  { type: "irregular", base: "Slit", past: "Slit", participle: "Slit", esPres: "Cortar / Hacer una raja", esPast: "Cortó / Hizo una raja", esPart: "Cortado" },
  { type: "irregular", base: "Bust", past: "Bust / Busted", participle: "Bust / Busted", esPres: "Reventar / Arrestar (informal)", esPast: "Reventó / Arrestó", esPart: "Reventado / Arrestado" },
  { type: "irregular", base: "Forecast", past: "Forecast", participle: "Forecast", esPres: "Pronosticar", esPast: "Pronosticó", esPart: "Pronosticado" },

  // ─── TECNOLOGÍA Y REDES SOCIALES ───────────────────────────────
  { type: "regular", sound: "d", base: "Design", past: "Designed", participle: "Designed", esPres: "Diseñar", esPast: "Diseñó", esPart: "Diseñado" },
  { type: "regular", sound: "d", base: "Install", past: "Installed", participle: "Installed", esPres: "Instalar", esPast: "Instaló", esPart: "Instalado" },
  { type: "regular", sound: "id", base: "Disconnect", past: "Disconnected", participle: "Disconnected", esPres: "Desconectar", esPast: "Desconectó", esPart: "Desconectado" },
  { type: "regular", sound: "d", base: "Plug", past: "Plugged", participle: "Plugged", esPres: "Enchufar", esPast: "Enchufó", esPart: "Enchufado" },
  { type: "regular", sound: "d", base: "Unplug", past: "Unplugged", participle: "Unplugged", esPres: "Desenchufar", esPast: "Desenchufó", esPart: "Desenchufado" },
  { type: "regular", sound: "d", base: "Charge", past: "Charged", participle: "Charged", esPres: "Cargar", esPast: "Cargó", esPart: "Cargado" },
  { type: "regular", sound: "id", base: "Delete", past: "Deleted", participle: "Deleted", esPres: "Eliminar / Borrar", esPast: "Eliminó / Borró", esPart: "Eliminado / Borrado" },
  { type: "regular", sound: "d", base: "Scan", past: "Scanned", participle: "Scanned", esPres: "Escanear", esPast: "Escaneó", esPart: "Escaneado" },
  { type: "regular", sound: "id", base: "Paste", past: "Pasted", participle: "Pasted", esPres: "Pegar", esPast: "Pegó", esPart: "Pegado" },
  { type: "regular", sound: "t", base: "Click", past: "Clicked", participle: "Clicked", esPres: "Hacer clic", esPast: "Hizo clic", esPart: "Hecho clic" },
  { type: "regular", sound: "t", base: "Tap", past: "Tapped", participle: "Tapped", esPres: "Tocar / Pulsar", esPast: "Tocó / Pulsó", esPart: "Tocado / Pulsado" },
  { type: "regular", sound: "t", base: "Swipe", past: "Swiped", participle: "Swiped", esPres: "Deslizar", esPast: "Deslizó", esPart: "Deslizado" },
  { type: "regular", sound: "d", base: "Browse", past: "Browsed", participle: "Browsed", esPres: "Navegar / Explorar", esPast: "Navegó / Exploró", esPart: "Navegado / Explorado" },
  { type: "regular", sound: "id", base: "Chat", past: "Chatted", participle: "Chatted", esPres: "Chatear / Conversar", esPast: "Chateó / Conversó", esPart: "Chateado / Conversado" },
  { type: "regular", sound: "id", base: "Text", past: "Texted", participle: "Texted", esPres: "Enviar un mensaje de texto", esPast: "Envió un mensaje de texto", esPart: "Enviado un mensaje de texto" },
  { type: "regular", sound: "d", base: "Phone", past: "Phoned", participle: "Phoned", esPres: "Llamar por teléfono", esPast: "Llamó por teléfono", esPart: "Llamado por teléfono" },
  { type: "regular", sound: "d", base: "Email", past: "Emailed", participle: "Emailed", esPres: "Enviar un correo", esPast: "Envió un correo", esPart: "Enviado un correo" },
  { type: "regular", sound: "id", base: "Post", past: "Posted", participle: "Posted", esPres: "Publicar", esPast: "Publicó", esPart: "Publicado" },
  { type: "regular", sound: "d", base: "Share", past: "Shared", participle: "Shared", esPres: "Compartir", esPast: "Compartió", esPart: "Compartido" },
  { type: "regular", sound: "d", base: "Subscribe", past: "Subscribed", participle: "Subscribed", esPres: "Suscribirse", esPast: "Se suscribió", esPart: "Suscrito" },
  { type: "regular", sound: "d", base: "Unfollow", past: "Unfollowed", participle: "Unfollowed", esPres: "Dejar de seguir", esPast: "Dejó de seguir", esPart: "Dejado de seguir" },
  { type: "regular", sound: "t", base: "Block", past: "Blocked", participle: "Blocked", esPres: "Bloquear", esPast: "Bloqueó", esPart: "Bloqueado" },
  { type: "regular", sound: "id", base: "Mute", past: "Muted", participle: "Muted", esPres: "Silenciar", esPast: "Silenció", esPart: "Silenciado" },
  { type: "regular", sound: "id", base: "Record", past: "Recorded", participle: "Recorded", esPres: "Grabar", esPast: "Grabó", esPart: "Grabado" },
  { type: "regular", sound: "d", base: "Film", past: "Filmed", participle: "Filmed", esPres: "Filmar", esPast: "Filmó", esPart: "Filmado" },
  { type: "regular", sound: "d", base: "Stream", past: "Streamed", participle: "Streamed", esPres: "Transmitir en vivo", esPast: "Transmitió en vivo", esPart: "Transmitido en vivo" },
  { type: "regular", sound: "t", base: "Publish", past: "Published", participle: "Published", esPres: "Publicar", esPast: "Publicó", esPart: "Publicado" },
  { type: "regular", sound: "id", base: "Translate", past: "Translated", participle: "Translated", esPres: "Traducir", esPast: "Tradujo", esPart: "Traducido" },
  { type: "regular", sound: "t", base: "Pronounce", past: "Pronounced", participle: "Pronounced", esPres: "Pronunciar", esPast: "Pronunció", esPart: "Pronunciado" },

  // ─── CASA Y RUTINA DIARIA ───────────────────────────────────────
  { type: "regular", sound: "t", base: "Watch", past: "Watched", participle: "Watched", esPres: "Mirar / Observar", esPast: "Miró / Observó", esPart: "Mirado / Observado" },
  { type: "regular", sound: "t", base: "Brush", past: "Brushed", participle: "Brushed", esPres: "Cepillar", esPast: "Cepilló", esPart: "Cepillado" },
  { type: "regular", sound: "d", base: "Comb", past: "Combed", participle: "Combed", esPres: "Peinar", esPast: "Peinó", esPart: "Peinado" },
  { type: "regular", sound: "d", base: "Iron", past: "Ironed", participle: "Ironed", esPres: "Planchar", esPast: "Planchó", esPart: "Planchado" },
  { type: "regular", sound: "d", base: "Vacuum", past: "Vacuumed", participle: "Vacuumed", esPres: "Aspirar", esPast: "Aspiró", esPart: "Aspirado" },
  { type: "regular", sound: "id", base: "Dust", past: "Dusted", participle: "Dusted", esPres: "Quitar el polvo", esPast: "Quitó el polvo", esPart: "Quitado el polvo" },
  { type: "regular", sound: "d", base: "Water", past: "Watered", participle: "Watered", esPres: "Regar", esPast: "Regó", esPart: "Regado" },
  { type: "regular", sound: "id", base: "Paint", past: "Painted", participle: "Painted", esPres: "Pintar", esPast: "Pintó", esPart: "Pintado" },
  { type: "regular", sound: "d", base: "Relax", past: "Relaxed", participle: "Relaxed", esPres: "Relajarse", esPast: "Se relajó", esPart: "Relajado" },
  { type: "regular", sound: "id", base: "Rest", past: "Rested", participle: "Rested", esPres: "Descansar", esPast: "Descansó", esPart: "Descansado" },
  { type: "regular", sound: "d", base: "Breathe", past: "Breathed", participle: "Breathed", esPres: "Respirar", esPast: "Respiró", esPart: "Respirado" },
  { type: "regular", sound: "d", base: "Stretch", past: "Stretched", participle: "Stretched", esPres: "Estirarse", esPast: "Se estiró", esPart: "Estirado" },
  { type: "regular", sound: "d", base: "Jog", past: "Jogged", participle: "Jogged", esPres: "Trotar", esPast: "Trotó", esPart: "Trotado" },
  { type: "regular", sound: "t", base: "Skip", past: "Skipped", participle: "Skipped", esPres: "Saltar / Saltarse", esPast: "Saltó / Se saltó", esPart: "Saltado" },

  // ─── EMOCIONES Y COMUNICACIÓN ───────────────────────────────────
  { type: "regular", sound: "t", base: "Laugh", past: "Laughed", participle: "Laughed", esPres: "Reír", esPast: "Rio", esPart: "Reído" },
  { type: "regular", sound: "d", base: "Cry", past: "Cried", participle: "Cried", esPres: "Llorar", esPast: "Lloró", esPart: "Llorado" },
  { type: "regular", sound: "d", base: "Smile", past: "Smiled", participle: "Smiled", esPres: "Sonreír", esPast: "Sonrió", esPart: "Sonreído" },
  { type: "regular", sound: "id", base: "Shout", past: "Shouted", participle: "Shouted", esPres: "Gritar", esPast: "Gritó", esPart: "Gritado" },
  { type: "regular", sound: "d", base: "Whisper", past: "Whispered", participle: "Whispered", esPres: "Susurrar", esPast: "Susurró", esPart: "Susurrado" },
  { type: "regular", sound: "d", base: "Scream", past: "Screamed", participle: "Screamed", esPres: "Chillar / Gritar", esPast: "Chilló / Gritó", esPart: "Chillado / Gritado" },
  { type: "regular", sound: "d", base: "Agree", past: "Agreed", participle: "Agreed", esPres: "Estar de acuerdo / Acordar", esPast: "Estuvo de acuerdo / Acordó", esPart: "Acordado" },
  { type: "regular", sound: "d", base: "Disagree", past: "Disagreed", participle: "Disagreed", esPres: "Discrepar / No estar de acuerdo", esPast: "Discrepó / No estuvo de acuerdo", esPart: "Discrepado" },
  { type: "regular", sound: "d", base: "Argue", past: "Argued", participle: "Argued", esPres: "Discutir / Argumentar", esPast: "Discutió / Argumentó", esPart: "Discutido / Argumentado" },
  { type: "regular", sound: "d", base: "Complain", past: "Complained", participle: "Complained", esPres: "Quejarse", esPast: "Se quejó", esPart: "Quejado" },
  { type: "regular", sound: "d", base: "Apologize", past: "Apologized", participle: "Apologized", esPres: "Disculparse / Pedir perdón", esPast: "Se disculpó / Pidió perdón", esPart: "Disculpado" },
  { type: "regular", sound: "t", base: "Thank", past: "Thanked", participle: "Thanked", esPres: "Agradecer", esPast: "Agradeció", esPart: "Agradecido" },
  { type: "regular", sound: "id", base: "Congratulate", past: "Congratulated", participle: "Congratulated", esPres: "Felicitar", esPast: "Felicitó", esPart: "Felicitado" },
  { type: "regular", sound: "id", base: "Celebrate", past: "Celebrated", participle: "Celebrated", esPres: "Celebrar", esPast: "Celebró", esPart: "Celebrado" },

  // ─── ESCUELA Y TRABAJO ──────────────────────────────────────────
  { type: "regular", sound: "d", base: "Memorize", past: "Memorized", participle: "Memorized", esPres: "Memorizar", esPast: "Memorizó", esPart: "Memorizado" },
  { type: "regular", sound: "d", base: "Revise", past: "Revised", participle: "Revised", esPres: "Revisar / Corregir", esPast: "Revisó / Corrigió", esPart: "Revisado / Corregido" },
  { type: "regular", sound: "d", base: "Summarize", past: "Summarized", participle: "Summarized", esPres: "Resumir", esPast: "Resumió", esPart: "Resumido" },
  { type: "regular", sound: "id", base: "Highlight", past: "Highlighted", participle: "Highlighted", esPres: "Resaltar / Subrayar", esPast: "Resaltó / Subrayó", esPart: "Resaltado / Subrayado" },
  { type: "regular", sound: "d", base: "Underline", past: "Underlined", participle: "Underlined", esPres: "Subrayar", esPast: "Subrayó", esPart: "Subrayado" },
  { type: "regular", sound: "d", base: "Circle", past: "Circled", participle: "Circled", esPres: "Encerrar en un círculo", esPast: "Encerró en un círculo", esPart: "Encerrado en un círculo" },
  { type: "regular", sound: "id", base: "Grade", past: "Graded", participle: "Graded", esPres: "Calificar", esPast: "Calificó", esPart: "Calificado" },
  { type: "regular", sound: "d", base: "Score", past: "Scored", participle: "Scored", esPres: "Anotar / Marcar un punto", esPast: "Anotó / Marcó un punto", esPart: "Anotado / Marcado" },
  { type: "regular", sound: "t", base: "Pass", past: "Passed", participle: "Passed", esPres: "Aprobar / Pasar", esPast: "Aprobó / Pasó", esPart: "Aprobado / Pasado" },
  { type: "regular", sound: "id", base: "Graduate", past: "Graduated", participle: "Graduated", esPres: "Graduarse", esPast: "Se graduó", esPart: "Graduado" },
  { type: "regular", sound: "d", base: "Enroll", past: "Enrolled", participle: "Enrolled", esPres: "Inscribirse / Matricularse", esPast: "Se inscribió / Se matriculó", esPart: "Inscrito / Matriculado" },
  { type: "regular", sound: "d", base: "Register", past: "Registered", participle: "Registered", esPres: "Registrarse / Inscribirse", esPast: "Se registró / Se inscribió", esPart: "Registrado / Inscrito" },
  { type: "regular", sound: "d", base: "Interview", past: "Interviewed", participle: "Interviewed", esPres: "Entrevistar", esPast: "Entrevistó", esPart: "Entrevistado" },
  { type: "regular", sound: "d", base: "Fire", past: "Fired", participle: "Fired", esPres: "Despedir", esPast: "Despidió", esPart: "Despedido" },
  { type: "regular", sound: "id", base: "Promote", past: "Promoted", participle: "Promoted", esPres: "Ascender / Promover", esPast: "Ascendió / Promovió", esPart: "Ascendido / Promovido" },
  { type: "regular", sound: "d", base: "Retire", past: "Retired", participle: "Retired", esPres: "Jubilarse / Retirarse", esPast: "Se jubiló / Se retiró", esPart: "Jubilado / Retirado" },
  { type: "regular", sound: "d", base: "Resign", past: "Resigned", participle: "Resigned", esPres: "Renunciar / Dimitir", esPast: "Renunció / Dimitió", esPart: "Renunciado / Dimitido" },
  { type: "regular", sound: "id", base: "Negotiate", past: "Negotiated", participle: "Negotiated", esPres: "Negociar", esPast: "Negoció", esPart: "Negociado" },
  { type: "regular", sound: "d", base: "Sign", past: "Signed", participle: "Signed", esPres: "Firmar", esPast: "Firmó", esPart: "Firmado" },
  { type: "regular", sound: "d", base: "Define", past: "Defined", participle: "Defined", esPres: "Definir", esPast: "Definió", esPart: "Definido" },
  { type: "regular", sound: "d", base: "Analyze", past: "Analyzed", participle: "Analyzed", esPres: "Analizar", esPast: "Analizó", esPart: "Analizado" },
  { type: "regular", sound: "id", base: "Contrast", past: "Contrasted", participle: "Contrasted", esPres: "Contrastar", esPast: "Contrastó", esPart: "Contrastado" },
  { type: "regular", sound: "id", base: "Debate", past: "Debated", participle: "Debated", esPres: "Debatir", esPast: "Debatió", esPart: "Debatido" },
  { type: "regular", sound: "t", base: "Research", past: "Researched", participle: "Researched", esPres: "Investigar", esPast: "Investigó", esPart: "Investigado" },
  { type: "regular", sound: "id", base: "Investigate", past: "Investigated", participle: "Investigated", esPres: "Investigar", esPast: "Investigó", esPart: "Investigado" },
  { type: "regular", sound: "d", base: "Observe", past: "Observed", participle: "Observed", esPres: "Observar", esPast: "Observó", esPart: "Observado" },
  { type: "regular", sound: "id", base: "Experiment", past: "Experimented", participle: "Experimented", esPres: "Experimentar", esPast: "Experimentó", esPart: "Experimentado" },
  { type: "regular", sound: "id", base: "Conclude", past: "Concluded", participle: "Concluded", esPres: "Concluir", esPast: "Concluyó", esPart: "Concluido" },
  { type: "regular", sound: "id", base: "Calculate", past: "Calculated", participle: "Calculated", esPres: "Calcular", esPast: "Calculó", esPart: "Calculado" },
  { type: "regular", sound: "d", base: "Weigh", past: "Weighed", participle: "Weighed", esPres: "Pesar", esPast: "Pesó", esPart: "Pesado" },
  { type: "regular", sound: "id", base: "Estimate", past: "Estimated", participle: "Estimated", esPres: "Estimar / Calcular", esPast: "Estimó / Calculó", esPart: "Estimado / Calculado" },
  { type: "regular", sound: "t", base: "Guess", past: "Guessed", participle: "Guessed", esPres: "Adivinar / Suponer", esPast: "Adivinó / Supuso", esPart: "Adivinado / Supuesto" },
  { type: "regular", sound: "d", base: "Schedule", past: "Scheduled", participle: "Scheduled", esPres: "Programar / Agendar", esPast: "Programó / Agendó", esPart: "Programado / Agendado" },
  { type: "regular", sound: "d", base: "Arrange", past: "Arranged", participle: "Arranged", esPres: "Organizar / Arreglar", esPast: "Organizó / Arregló", esPart: "Organizado / Arreglado" },

  // ─── DINERO Y NEGOCIOS ───────────────────────────────────────────
  { type: "regular", sound: "t", base: "Wrap", past: "Wrapped", participle: "Wrapped", esPres: "Envolver", esPast: "Envolvió", esPart: "Envuelto" },
  { type: "regular", sound: "t", base: "Unwrap", past: "Unwrapped", participle: "Unwrapped", esPres: "Desenvolver", esPast: "Desenvolvió", esPart: "Desenvuelto" },
  { type: "regular", sound: "t", base: "Ship", past: "Shipped", participle: "Shipped", esPres: "Enviar / Despachar", esPast: "Envió / Despachó", esPart: "Enviado / Despachado" },
  { type: "regular", sound: "d", base: "Package", past: "Packaged", participle: "Packaged", esPres: "Empaquetar", esPast: "Empaquetó", esPart: "Empaquetado" },
  { type: "regular", sound: "t", base: "Purchase", past: "Purchased", participle: "Purchased", esPres: "Comprar / Adquirir", esPast: "Compró / Adquirió", esPart: "Comprado / Adquirido" },
  { type: "regular", sound: "t", base: "Lease", past: "Leased", participle: "Leased", esPres: "Arrendar", esPast: "Arrendó", esPart: "Arrendado" },
  { type: "regular", sound: "id", base: "Refund", past: "Refunded", participle: "Refunded", esPres: "Reembolsar", esPast: "Reembolsó", esPart: "Reembolsado" },
  { type: "regular", sound: "id", base: "Discount", past: "Discounted", participle: "Discounted", esPres: "Descontar / Rebajar", esPast: "Descontó / Rebajó", esPart: "Descontado / Rebajado" },
  { type: "regular", sound: "d", base: "Bargain", past: "Bargained", participle: "Bargained", esPres: "Regatear", esPast: "Regateó", esPart: "Regateado" },
  { type: "regular", sound: "id", base: "Budget", past: "Budgeted", participle: "Budgeted", esPres: "Presupuestar", esPast: "Presupuestó", esPart: "Presupuestado" },
  { type: "regular", sound: "id", base: "Donate", past: "Donated", participle: "Donated", esPres: "Donar", esPast: "Donó", esPart: "Donado" },
  { type: "regular", sound: "id", base: "Fund", past: "Funded", participle: "Funded", esPres: "Financiar", esPast: "Financió", esPart: "Financiado" },
  { type: "regular", sound: "d", base: "Sponsor", past: "Sponsored", participle: "Sponsored", esPres: "Patrocinar", esPast: "Patrocinó", esPart: "Patrocinado" },
  { type: "regular", sound: "t", base: "Tax", past: "Taxed", participle: "Taxed", esPres: "Gravar / Cobrar impuestos", esPast: "Gravó / Cobró impuestos", esPart: "Gravado" },
  { type: "regular", sound: "d", base: "Bill", past: "Billed", participle: "Billed", esPres: "Facturar", esPast: "Facturó", esPart: "Facturado" },
  { type: "regular", sound: "d", base: "Owe", past: "Owed", participle: "Owed", esPres: "Deber", esPast: "Debió", esPart: "Debido" },
  { type: "regular", sound: "d", base: "Loan", past: "Loaned", participle: "Loaned", esPres: "Prestar", esPast: "Prestó", esPart: "Prestado" },
  { type: "regular", sound: "d", base: "Transfer", past: "Transferred", participle: "Transferred", esPres: "Transferir", esPast: "Transfirió", esPart: "Transferido" },

  // ─── VIAJES Y TRANSPORTE ─────────────────────────────────────────
  { type: "regular", sound: "id", base: "Depart", past: "Departed", participle: "Departed", esPres: "Partir / Salir", esPast: "Partió / Salió", esPart: "Partido / Salido" },
  { type: "regular", sound: "id", base: "Land", past: "Landed", participle: "Landed", esPres: "Aterrizar", esPast: "Aterrizó", esPart: "Aterrizado" },
  { type: "regular", sound: "id", base: "Board", past: "Boarded", participle: "Boarded", esPres: "Abordar / Embarcar", esPast: "Abordó / Embarcó", esPart: "Abordado / Embarcado" },
  { type: "regular", sound: "d", base: "Reserve", past: "Reserved", participle: "Reserved", esPres: "Reservar", esPast: "Reservó", esPart: "Reservado" },
  { type: "regular", sound: "t", base: "Book", past: "Booked", participle: "Booked", esPres: "Reservar", esPast: "Reservó", esPart: "Reservado" },
  { type: "regular", sound: "d", base: "Cancel", past: "Cancelled", participle: "Cancelled", esPres: "Cancelar", esPast: "Canceló", esPart: "Cancelado" },
  { type: "regular", sound: "d", base: "Confirm", past: "Confirmed", participle: "Confirmed", esPres: "Confirmar", esPast: "Confirmó", esPart: "Confirmado" },
  { type: "regular", sound: "t", base: "Pack", past: "Packed", participle: "Packed", esPres: "Empacar / Hacer las maletas", esPast: "Empacó / Hizo las maletas", esPart: "Empacado" },
  { type: "regular", sound: "t", base: "Unpack", past: "Unpacked", participle: "Unpacked", esPres: "Desempacar", esPast: "Desempacó", esPart: "Desempacado" },
  { type: "regular", sound: "id", base: "Load", past: "Loaded", participle: "Loaded", esPres: "Cargar", esPast: "Cargó", esPart: "Cargado" },
  { type: "regular", sound: "id", base: "Unload", past: "Unloaded", participle: "Unloaded", esPres: "Descargar", esPast: "Descargó", esPart: "Descargado" },
  { type: "regular", sound: "t", base: "Park", past: "Parked", participle: "Parked", esPres: "Estacionar / Aparcar", esPast: "Estacionó / Aparcó", esPart: "Estacionado / Aparcado" },
  { type: "regular", sound: "d", base: "Tow", past: "Towed", participle: "Towed", esPres: "Remolcar", esPast: "Remolcó", esPart: "Remolcado" },
  { type: "regular", sound: "d", base: "Fuel", past: "Fueled", participle: "Fueled", esPres: "Repostar / Abastecer de combustible", esPast: "Repostó / Abasteció", esPart: "Repostado" },
  { type: "regular", sound: "t", base: "Brake", past: "Braked", participle: "Braked", esPres: "Frenar", esPast: "Frenó", esPart: "Frenado" },
  { type: "regular", sound: "d", base: "Signal", past: "Signaled", participle: "Signaled", esPres: "Señalizar / Indicar", esPast: "Señalizó / Indicó", esPart: "Señalizado / Indicado" },
  { type: "regular", sound: "d", base: "Merge", past: "Merged", participle: "Merged", esPres: "Fusionar / Incorporarse (al tráfico)", esPast: "Fusionó / Se incorporó", esPart: "Fusionado / Incorporado" },
  { type: "regular", sound: "t", base: "Honk", past: "Honked", participle: "Honked", esPres: "Tocar la bocina", esPast: "Tocó la bocina", esPart: "Tocado la bocina" },

  // ─── COCINA ───────────────────────────────────────────────────
  { type: "regular", sound: "t", base: "Bake", past: "Baked", participle: "Baked", esPres: "Hornear", esPast: "Horneó", esPart: "Horneado" },
  { type: "regular", sound: "d", base: "Boil", past: "Boiled", participle: "Boiled", esPres: "Hervir", esPast: "Hirvió", esPart: "Hervido" },
  { type: "regular", sound: "d", base: "Fry", past: "Fried", participle: "Fried", esPres: "Freír", esPast: "Frio", esPart: "Frito" },
  { type: "regular", sound: "d", base: "Grill", past: "Grilled", participle: "Grilled", esPres: "Asar a la parrilla", esPast: "Asó a la parrilla", esPart: "Asado a la parrilla" },
  { type: "regular", sound: "id", base: "Roast", past: "Roasted", participle: "Roasted", esPres: "Asar / Tostar", esPast: "Asó / Tostó", esPart: "Asado / Tostado" },
  { type: "regular", sound: "t", base: "Chop", past: "Chopped", participle: "Chopped", esPres: "Picar / Cortar", esPast: "Picó / Cortó", esPart: "Picado / Cortado" },
  { type: "regular", sound: "d", base: "Peel", past: "Peeled", participle: "Peeled", esPres: "Pelar", esPast: "Peló", esPart: "Pelado" },
  { type: "regular", sound: "d", base: "Stir", past: "Stirred", participle: "Stirred", esPres: "Revolver / Remover", esPast: "Revolvió / Removió", esPart: "Revuelto / Removido" },
  { type: "regular", sound: "id", base: "Blend", past: "Blended", participle: "Blended", esPres: "Licuar / Mezclar", esPast: "Licuó / Mezcló", esPart: "Licuado / Mezclado" },
  { type: "regular", sound: "d", base: "Season", past: "Seasoned", participle: "Seasoned", esPres: "Sazonar / Condimentar", esPast: "Sazonó / Condimentó", esPart: "Sazonado / Condimentado" },
  { type: "regular", sound: "id", base: "Taste", past: "Tasted", participle: "Tasted", esPres: "Probar / Saborear", esPast: "Probó / Saboreó", esPart: "Probado / Saboreado" },
  { type: "regular", sound: "t", base: "Garnish", past: "Garnished", participle: "Garnished", esPres: "Adornar / Decorar (un plato)", esPast: "Adornó / Decoró", esPart: "Adornado / Decorado" },

  // ─── CLIMA ───────────────────────────────────────────────────
  { type: "regular", sound: "d", base: "Snow", past: "Snowed", participle: "Snowed", esPres: "Nevar", esPast: "Nevó", esPart: "Nevado" },


  // ─── SEGUNDA TANDA — REPARACIONES, SALUD, DEPORTES, CLIMA, FAMILIA,
  // COMPRAS, COMUNICACIÓN, TECNOLOGÍA, ARTE, ANIMALES, LEY, CIENCIA,
  // MOVIMIENTO, LIMPIEZA Y EMOCIONES ──────────────────────────────
  { type: "regular", sound: "d", base: "Repair", past: "Repaired", participle: "Repaired", esPres: "Reparar", esPast: "Reparó", esPart: "Reparado" },
  { type: "regular", sound: "d", base: "Assemble", past: "Assembled", participle: "Assembled", esPres: "Ensamblar / Armar", esPast: "Ensambló / Armó", esPart: "Ensamblado / Armado" },
  { type: "regular", sound: "d", base: "Disassemble", past: "Disassembled", participle: "Disassembled", esPres: "Desensamblar / Desarmar", esPast: "Desensambló / Desarmó", esPart: "Desensamblado / Desarmado" },
  { type: "regular", sound: "d", base: "Hammer", past: "Hammered", participle: "Hammered", esPres: "Martillar", esPast: "Martilló", esPart: "Martillado" },
  { type: "regular", sound: "d", base: "Drill", past: "Drilled", participle: "Drilled", esPres: "Taladrar", esPast: "Taladró", esPart: "Taladrado" },
  { type: "regular", sound: "d", base: "Nail", past: "Nailed", participle: "Nailed", esPres: "Clavar", esPast: "Clavó", esPart: "Clavado" },
  { type: "regular", sound: "d", base: "Screw", past: "Screwed", participle: "Screwed", esPres: "Atornillar", esPast: "Atornilló", esPart: "Atornillado" },
  { type: "regular", sound: "d", base: "Glue", past: "Glued", participle: "Glued", esPres: "Pegar con pegamento", esPast: "Pegó con pegamento", esPart: "Pegado con pegamento" },
  { type: "regular", sound: "id", base: "Weld", past: "Welded", participle: "Welded", esPres: "Soldar", esPast: "Soldó", esPart: "Soldado" },
  { type: "regular", sound: "id", base: "Sand", past: "Sanded", participle: "Sanded", esPres: "Lijar", esPast: "Lijó", esPart: "Lijado" },
  { type: "regular", sound: "t", base: "Polish", past: "Polished", participle: "Polished", esPres: "Pulir / Lustrar", esPast: "Pulió / Lustró", esPart: "Pulido / Lustrado" },
  { type: "regular", sound: "id", base: "Lubricate", past: "Lubricated", participle: "Lubricated", esPres: "Lubricar", esPast: "Lubricó", esPart: "Lubricado" },
  { type: "regular", sound: "d", base: "Tighten", past: "Tightened", participle: "Tightened", esPres: "Apretar", esPast: "Apretó", esPart: "Apretado" },
  { type: "regular", sound: "d", base: "Loosen", past: "Loosened", participle: "Loosened", esPres: "Aflojar", esPast: "Aflojó", esPart: "Aflojado" },
  { type: "regular", sound: "d", base: "Level", past: "Leveled", participle: "Leveled", esPres: "Nivelar", esPast: "Niveló", esPart: "Nivelado" },
  { type: "regular", sound: "d", base: "Wire", past: "Wired", participle: "Wired", esPres: "Cablear / Conectar con cables", esPast: "Cableó", esPart: "Cableado" },
  { type: "regular", sound: "id", base: "Insulate", past: "Insulated", participle: "Insulated", esPres: "Aislar", esPast: "Aisló", esPart: "Aislado" },
  { type: "regular", sound: "d", base: "Plaster", past: "Plastered", participle: "Plastered", esPres: "Enyesar / Emplastecer", esPast: "Enyesó", esPart: "Enyesado" },
  { type: "regular", sound: "t", base: "Demolish", past: "Demolished", participle: "Demolished", esPres: "Demoler", esPast: "Demolió", esPart: "Demolido" },
  { type: "regular", sound: "id", base: "Renovate", past: "Renovated", participle: "Renovated", esPres: "Renovar", esPast: "Renovó", esPart: "Renovado" },
  { type: "regular", sound: "d", base: "Remodel", past: "Remodeled", participle: "Remodeled", esPres: "Remodelar", esPast: "Remodeló", esPart: "Remodelado" },
  { type: "regular", sound: "t", base: "Patch", past: "Patched", participle: "Patched", esPres: "Remendar / Parchar", esPast: "Remendó / Parchó", esPart: "Remendado / Parchado" },
  { type: "regular", sound: "d", base: "Seal", past: "Sealed", participle: "Sealed", esPres: "Sellar", esPast: "Selló", esPart: "Sellado" },
  { type: "regular", sound: "id", base: "Mount", past: "Mounted", participle: "Mounted", esPres: "Montar", esPast: "Montó", esPart: "Montado" },
  { type: "regular", sound: "d", base: "Heal", past: "Healed", participle: "Healed", esPres: "Sanar / Curar", esPast: "Sanó / Curó", esPart: "Sanado / Curado" },
  { type: "regular", sound: "d", base: "Cure", past: "Cured", participle: "Cured", esPres: "Curar", esPast: "Curó", esPart: "Curado" },
  { type: "regular", sound: "d", base: "Diagnose", past: "Diagnosed", participle: "Diagnosed", esPres: "Diagnosticar", esPast: "Diagnosticó", esPart: "Diagnosticado" },
  { type: "regular", sound: "d", base: "Prescribe", past: "Prescribed", participle: "Prescribed", esPres: "Recetar", esPast: "Recetó", esPart: "Recetado" },
  { type: "regular", sound: "id", base: "Vaccinate", past: "Vaccinated", participle: "Vaccinated", esPres: "Vacunar", esPast: "Vacunó", esPart: "Vacunado" },
  { type: "regular", sound: "id", base: "Inject", past: "Injected", participle: "Injected", esPres: "Inyectar", esPast: "Inyectó", esPart: "Inyectado" },
  { type: "regular", sound: "d", base: "Bandage", past: "Bandaged", participle: "Bandaged", esPres: "Vendar", esPast: "Vendó", esPart: "Vendado" },
  { type: "regular", sound: "d", base: "Examine", past: "Examined", participle: "Examined", esPres: "Examinar", esPast: "Examinó", esPart: "Examinado" },
  { type: "regular", sound: "d", base: "Recover", past: "Recovered", participle: "Recovered", esPres: "Recuperarse", esPast: "Se recuperó", esPart: "Recuperado" },
  { type: "regular", sound: "id", base: "Infect", past: "Infected", participle: "Infected", esPres: "Infectar", esPast: "Infectó", esPart: "Infectado" },
  { type: "regular", sound: "d", base: "Bruise", past: "Bruised", participle: "Bruised", esPres: "Magullar / Amoratar", esPast: "Magulló", esPart: "Magullado" },
  { type: "regular", sound: "d", base: "Sprain", past: "Sprained", participle: "Sprained", esPres: "Torcerse (un tobillo)", esPast: "Se torció", esPart: "Torcido" },
  { type: "regular", sound: "id", base: "Faint", past: "Fainted", participle: "Fainted", esPres: "Desmayarse", esPast: "Se desmayó", esPart: "Desmayado" },
  { type: "regular", sound: "t", base: "Cough", past: "Coughed", participle: "Coughed", esPres: "Toser", esPast: "Tosió", esPart: "Tosido" },
  { type: "regular", sound: "d", base: "Sneeze", past: "Sneezed", participle: "Sneezed", esPres: "Estornudar", esPast: "Estornudó", esPart: "Estornudado" },
  { type: "regular", sound: "t", base: "Itch", past: "Itched", participle: "Itched", esPres: "Picar (comezón)", esPast: "Picó", esPart: "Picado" },
  { type: "regular", sound: "id", base: "Vomit", past: "Vomited", participle: "Vomited", esPres: "Vomitar", esPast: "Vomitó", esPart: "Vomitado" },
  { type: "regular", sound: "t", base: "Choke", past: "Choked", participle: "Choked", esPres: "Asfixiarse / Atragantarse", esPast: "Se asfixió / Se atragantó", esPart: "Asfixiado / Atragantado" },
  { type: "regular", sound: "t", base: "Kick", past: "Kicked", participle: "Kicked", esPres: "Patear", esPast: "Pateó", esPart: "Pateado" },
  { type: "regular", sound: "t", base: "Pitch", past: "Pitched", participle: "Pitched", esPres: "Lanzar (béisbol)", esPast: "Lanzó", esPart: "Lanzado" },
  { type: "regular", sound: "d", base: "Dribble", past: "Dribbled", participle: "Dribbled", esPres: "Driblar / Regatear", esPast: "Dribló / Regateó", esPart: "Driblado / Regateado" },
  { type: "regular", sound: "d", base: "Tackle", past: "Tackled", participle: "Tackled", esPres: "Placar / Atajar", esPast: "Placó / Atajó", esPart: "Placado / Atajado" },
  { type: "regular", sound: "t", base: "Spike", past: "Spiked", participle: "Spiked", esPres: "Rematar (voleibol)", esPast: "Remató", esPart: "Rematado" },
  { type: "regular", sound: "id", base: "Sprint", past: "Sprinted", participle: "Sprinted", esPres: "Esprintar / Correr a toda velocidad", esPast: "Esprintó", esPart: "Esprintado" },
  { type: "regular", sound: "t", base: "Race", past: "Raced", participle: "Raced", esPres: "Competir en una carrera", esPast: "Compitió", esPart: "Competido" },
  { type: "regular", sound: "d", base: "Referee", past: "Refereed", participle: "Refereed", esPres: "Arbitrar", esPast: "Arbitró", esPart: "Arbitrado" },
  { type: "regular", sound: "t", base: "Coach", past: "Coached", participle: "Coached", esPres: "Entrenar", esPast: "Entrenó", esPart: "Entrenado" },
  { type: "regular", sound: "d", base: "Train", past: "Trained", participle: "Trained", esPres: "Entrenar / Capacitar", esPast: "Entrenó / Capacitó", esPart: "Entrenado / Capacitado" },
  { type: "regular", sound: "id", base: "Lift", past: "Lifted", participle: "Lifted", esPres: "Levantar", esPast: "Levantó", esPart: "Levantado" },
  { type: "regular", sound: "d", base: "Wrestle", past: "Wrestled", participle: "Wrestled", esPres: "Luchar (lucha libre)", esPast: "Luchó", esPart: "Luchado" },
  { type: "regular", sound: "id", base: "Skate", past: "Skated", participle: "Skated", esPres: "Patinar", esPast: "Patinó", esPart: "Patinado" },
  { type: "regular", sound: "d", base: "Ski", past: "Skied", participle: "Skied", esPres: "Esquiar", esPast: "Esquió", esPart: "Esquiado" },
  { type: "regular", sound: "t", base: "Surf", past: "Surfed", participle: "Surfed", esPres: "Surfear", esPast: "Surfeó", esPart: "Surfeado" },
  { type: "regular", sound: "d", base: "Paddle", past: "Paddled", participle: "Paddled", esPres: "Remar / Pedalear (canoa)", esPast: "Remó", esPart: "Remado" },
  { type: "regular", sound: "d", base: "Row", past: "Rowed", participle: "Rowed", esPres: "Remar", esPast: "Remó", esPart: "Remado" },
  { type: "regular", sound: "d", base: "Cycle", past: "Cycled", participle: "Cycled", esPres: "Andar en bicicleta", esPast: "Anduvo en bicicleta", esPart: "Andado en bicicleta" },
  { type: "regular", sound: "d", base: "Thunder", past: "Thundered", participle: "Thundered", esPres: "Tronar", esPast: "Tronó", esPart: "Tronado" },
  { type: "regular", sound: "d", base: "Drizzle", past: "Drizzled", participle: "Drizzled", esPres: "Lloviznar", esPast: "Llovió", esPart: "Lloviznado" },
  { type: "regular", sound: "id", base: "Flood", past: "Flooded", participle: "Flooded", esPres: "Inundar", esPast: "Inundó", esPart: "Inundado" },
  { type: "regular", sound: "id", base: "Erupt", past: "Erupted", participle: "Erupted", esPres: "Erupcionar", esPast: "Erupcionó", esPart: "Erupcionado" },
  { type: "regular", sound: "d", base: "Wither", past: "Withered", participle: "Withered", esPres: "Marchitarse", esPast: "Se marchitó", esPart: "Marchitado" },
  { type: "regular", sound: "d", base: "Bloom", past: "Bloomed", participle: "Bloomed", esPres: "Florecer", esPast: "Floreció", esPart: "Florecido" },
  { type: "regular", sound: "d", base: "Blossom", past: "Blossomed", participle: "Blossomed", esPres: "Florecer / Dar flores", esPast: "Floreció", esPart: "Florecido" },
  { type: "regular", sound: "id", base: "Sprout", past: "Sprouted", participle: "Sprouted", esPres: "Brotar", esPast: "Brotó", esPart: "Brotado" },
  { type: "regular", sound: "id", base: "Wilt", past: "Wilted", participle: "Wilted", esPres: "Marchitarse", esPast: "Se marchitó", esPart: "Marchitado" },
  { type: "regular", sound: "d", base: "Decay", past: "Decayed", participle: "Decayed", esPres: "Descomponerse / Deteriorarse", esPast: "Se descompuso", esPart: "Descompuesto" },
  { type: "regular", sound: "id", base: "Rot", past: "Rotted", participle: "Rotted", esPres: "Pudrirse", esPast: "Se pudrió", esPart: "Podrido" },
  { type: "regular", sound: "id", base: "Evaporate", past: "Evaporated", participle: "Evaporated", esPres: "Evaporarse", esPast: "Se evaporó", esPart: "Evaporado" },
  { type: "regular", sound: "t", base: "Condense", past: "Condensed", participle: "Condensed", esPres: "Condensarse", esPast: "Se condensó", esPart: "Condensado" },
  { type: "regular", sound: "d", base: "Marry", past: "Married", participle: "Married", esPres: "Casarse (con)", esPast: "Se casó (con)", esPart: "Casado" },
  { type: "regular", sound: "d", base: "Engage", past: "Engaged", participle: "Engaged", esPres: "Comprometerse", esPast: "Se comprometió", esPart: "Comprometido" },
  { type: "regular", sound: "d", base: "Propose", past: "Proposed", participle: "Proposed", esPres: "Proponer matrimonio", esPast: "Propuso matrimonio", esPart: "Propuesto matrimonio" },
  { type: "regular", sound: "id", base: "Adopt", past: "Adopted", participle: "Adopted", esPres: "Adoptar", esPast: "Adoptó", esPart: "Adoptado" },
  { type: "regular", sound: "d", base: "Raise", past: "Raised", participle: "Raised", esPres: "Criar / Educar", esPast: "Crió / Educó", esPart: "Criado / Educado" },
  { type: "irregular", base: "Babysit", past: "Babysat", participle: "Babysat", esPres: "Cuidar niños", esPast: "Cuidó niños", esPart: "Cuidado niños" },
  { type: "regular", sound: "id", base: "Inherit", past: "Inherited", participle: "Inherited", esPres: "Heredar", esPast: "Heredó", esPart: "Heredado" },
  { type: "regular", sound: "id", base: "Trade", past: "Traded", participle: "Traded", esPres: "Comerciar / Intercambiar", esPast: "Comerció / Intercambió", esPart: "Comerciado / Intercambiado" },
  { type: "regular", sound: "id", base: "Draft", past: "Drafted", participle: "Drafted", esPres: "Redactar (un borrador)", esPast: "Redactó", esPart: "Redactado" },
  { type: "irregular", base: "Proofread", past: "Proofread", participle: "Proofread", esPres: "Corregir pruebas / Revisar texto", esPast: "Corrigió pruebas", esPart: "Corregido pruebas" },
  { type: "regular", sound: "id", base: "Cite", past: "Cited", participle: "Cited", esPres: "Citar", esPast: "Citó", esPart: "Citado" },
  { type: "regular", sound: "id", base: "Quote", past: "Quoted", participle: "Quoted", esPres: "Citar / Cotizar", esPast: "Citó / Cotizó", esPart: "Citado / Cotizado" },
  { type: "regular", sound: "d", base: "Paraphrase", past: "Paraphrased", participle: "Paraphrased", esPres: "Parafrasear", esPast: "Parafraseó", esPart: "Parafraseado" },
  { type: "regular", sound: "d", base: "Censor", past: "Censored", participle: "Censored", esPres: "Censurar", esPast: "Censuró", esPart: "Censurado" },
  { type: "regular", sound: "id", base: "Code", past: "Coded", participle: "Coded", esPres: "Programar / Codificar", esPast: "Programó / Codificó", esPart: "Programado / Codificado" },
  { type: "regular", sound: "d", base: "Program", past: "Programmed", participle: "Programmed", esPres: "Programar", esPast: "Programó", esPart: "Programado" },
  { type: "regular", sound: "d", base: "Debug", past: "Debugged", participle: "Debugged", esPres: "Depurar (código)", esPast: "Depuró", esPart: "Depurado" },
  { type: "regular", sound: "d", base: "Compile", past: "Compiled", participle: "Compiled", esPres: "Compilar", esPast: "Compiló", esPart: "Compilado" },
  { type: "regular", sound: "id", base: "Execute", past: "Executed", participle: "Executed", esPres: "Ejecutar", esPast: "Ejecutó", esPart: "Ejecutado" },
  { type: "regular", sound: "d", base: "Uninstall", past: "Uninstalled", participle: "Uninstalled", esPres: "Desinstalar", esPast: "Desinstaló", esPart: "Desinstalado" },
  { type: "regular", sound: "id", base: "Upgrade", past: "Upgraded", participle: "Upgraded", esPres: "Actualizar (a una versión mejor)", esPast: "Actualizó", esPart: "Actualizado" },
  { type: "regular", sound: "d", base: "Restore", past: "Restored", participle: "Restored", esPres: "Restaurar / Restablecer", esPast: "Restauró / Restableció", esPart: "Restaurado / Restablecido" },
  { type: "regular", sound: "t", base: "Sync", past: "Synced", participle: "Synced", esPres: "Sincronizar", esPast: "Sincronizó", esPart: "Sincronizado" },
  { type: "regular", sound: "id", base: "Format", past: "Formatted", participle: "Formatted", esPres: "Formatear", esPast: "Formateó", esPart: "Formateado" },
  { type: "regular", sound: "id", base: "Encrypt", past: "Encrypted", participle: "Encrypted", esPres: "Encriptar / Cifrar", esPast: "Encriptó / Cifró", esPart: "Encriptado / Cifrado" },
  { type: "regular", sound: "id", base: "Decrypt", past: "Decrypted", participle: "Decrypted", esPres: "Desencriptar / Descifrar", esPast: "Desencriptó / Descifró", esPart: "Desencriptado / Descifrado" },
  { type: "regular", sound: "t", base: "Hack", past: "Hacked", participle: "Hacked", esPres: "Hackear", esPast: "Hackeó", esPart: "Hackeado" },
  { type: "regular", sound: "id", base: "Reboot", past: "Rebooted", participle: "Rebooted", esPres: "Reiniciar", esPast: "Reinició", esPart: "Reiniciado" },
  { type: "regular", sound: "t", base: "Sketch", past: "Sketched", participle: "Sketched", esPres: "Bosquejar / Esbozar", esPast: "Bosquejó / Esbozó", esPart: "Bosquejado / Esbozado" },
  { type: "regular", sound: "id", base: "Sculpt", past: "Sculpted", participle: "Sculpted", esPres: "Esculpir", esPast: "Esculpió", esPart: "Esculpido" },
  { type: "regular", sound: "d", base: "Carve", past: "Carved", participle: "Carved", esPres: "Tallar", esPast: "Talló", esPart: "Tallado" },
  { type: "regular", sound: "d", base: "Compose", past: "Composed", participle: "Composed", esPres: "Componer", esPast: "Compuso", esPart: "Compuesto" },
  { type: "regular", sound: "id", base: "Conduct", past: "Conducted", participle: "Conducted", esPres: "Dirigir (una orquesta)", esPast: "Dirigió", esPart: "Dirigido" },
  { type: "regular", sound: "id", base: "Animate", past: "Animated", participle: "Animated", esPres: "Animar", esPast: "Animó", esPart: "Animado" },
  { type: "regular", sound: "id", base: "Illustrate", past: "Illustrated", participle: "Illustrated", esPres: "Ilustrar", esPast: "Ilustró", esPart: "Ilustrado" },
  { type: "regular", sound: "t", base: "Photograph", past: "Photographed", participle: "Photographed", esPres: "Fotografiar", esPast: "Fotografió", esPart: "Fotografiado" },
  { type: "regular", sound: "id", base: "Exhibit", past: "Exhibited", participle: "Exhibited", esPres: "Exhibir", esPast: "Exhibió", esPart: "Exhibido" },
  { type: "regular", sound: "id", base: "Hunt", past: "Hunted", participle: "Hunted", esPres: "Cazar", esPast: "Cazó", esPart: "Cazado" },
  { type: "regular", sound: "t", base: "Fish", past: "Fished", participle: "Fished", esPres: "Pescar", esPast: "Pescó", esPart: "Pescado" },
  { type: "regular", sound: "t", base: "Trap", past: "Trapped", participle: "Trapped", esPres: "Atrapar", esPast: "Atrapó", esPart: "Atrapado" },
  { type: "regular", sound: "d", base: "Tame", past: "Tamed", participle: "Tamed", esPres: "Domesticar / Domar", esPast: "Domesticó / Domó", esPart: "Domesticado / Domado" },
  { type: "regular", sound: "d", base: "Graze", past: "Grazed", participle: "Grazed", esPres: "Pastar", esPast: "Pastó", esPart: "Pastado" },
  { type: "regular", sound: "t", base: "Hatch", past: "Hatched", participle: "Hatched", esPres: "Empollar / Nacer (de un huevo)", esPast: "Empolló / Nació", esPart: "Empollado / Nacido" },
  { type: "regular", sound: "id", base: "Migrate", past: "Migrated", participle: "Migrated", esPres: "Migrar", esPast: "Migró", esPart: "Migrado" },
  { type: "regular", sound: "d", base: "Groom", past: "Groomed", participle: "Groomed", esPres: "Acicalar / Cepillar (mascota)", esPast: "Acicaló / Cepilló", esPart: "Acicalado / Cepillado" },
  { type: "regular", sound: "d", base: "Sue", past: "Sued", participle: "Sued", esPres: "Demandar", esPast: "Demandó", esPart: "Demandado" },
  { type: "regular", sound: "d", base: "Testify", past: "Testified", participle: "Testified", esPres: "Testificar", esPast: "Testificó", esPart: "Testificado" },
  { type: "regular", sound: "t", base: "Sentence", past: "Sentenced", participle: "Sentenced", esPres: "Sentenciar / Condenar", esPast: "Sentenció / Condenó", esPart: "Sentenciado / Condenado" },
  { type: "regular", sound: "id", base: "Convict", past: "Convicted", participle: "Convicted", esPres: "Condenar / Declarar culpable", esPast: "Condenó", esPart: "Condenado" },
  { type: "regular", sound: "id", base: "Acquit", past: "Acquitted", participle: "Acquitted", esPres: "Absolver", esPast: "Absolvió", esPart: "Absuelto" },
  { type: "regular", sound: "d", base: "Appeal", past: "Appealed", participle: "Appealed", esPres: "Apelar", esPast: "Apeló", esPart: "Apelado" },
  { type: "regular", sound: "id", base: "Legislate", past: "Legislated", participle: "Legislated", esPres: "Legislar", esPast: "Legisló", esPart: "Legislado" },
  { type: "regular", sound: "id", base: "Elect", past: "Elected", participle: "Elected", esPres: "Elegir (por votación)", esPast: "Eligió", esPart: "Elegido" },
  { type: "regular", sound: "d", base: "Govern", past: "Governed", participle: "Governed", esPres: "Gobernar", esPast: "Gobernó", esPart: "Gobernado" },
  { type: "regular", sound: "id", base: "Regulate", past: "Regulated", participle: "Regulated", esPres: "Regular", esPast: "Reguló", esPart: "Regulado" },
  { type: "regular", sound: "id", base: "Prosecute", past: "Prosecuted", participle: "Prosecuted", esPres: "Procesar / Enjuiciar", esPast: "Procesó / Enjuició", esPart: "Procesado / Enjuiciado" },
  { type: "regular", sound: "d", base: "Hypothesize", past: "Hypothesized", participle: "Hypothesized", esPres: "Formular una hipótesis", esPast: "Formuló una hipótesis", esPart: "Formulado una hipótesis" },
  { type: "regular", sound: "d", base: "Classify", past: "Classified", participle: "Classified", esPres: "Clasificar", esPast: "Clasificó", esPart: "Clasificado" },
  { type: "regular", sound: "id", base: "Dissect", past: "Dissected", participle: "Dissected", esPres: "Diseccionar", esPast: "Diseccionó", esPart: "Diseccionado" },
  { type: "regular", sound: "id", base: "React", past: "Reacted", participle: "Reacted", esPres: "Reaccionar", esPast: "Reaccionó", esPart: "Reaccionado" },
  { type: "regular", sound: "d", base: "Dissolve", past: "Dissolved", participle: "Dissolved", esPres: "Disolver", esPast: "Disolvió", esPart: "Disuelto" },
  { type: "regular", sound: "d", base: "Filter", past: "Filtered", participle: "Filtered", esPres: "Filtrar", esPast: "Filtró", esPart: "Filtrado" },
  { type: "regular", sound: "d", base: "Enter", past: "Entered", participle: "Entered", esPres: "Entrar", esPast: "Entró", esPart: "Entrado" },
  { type: "regular", sound: "id", base: "Exit", past: "Exited", participle: "Exited", esPres: "Salir", esPast: "Salió", esPart: "Salido" },
  { type: "regular", sound: "t", base: "Rush", past: "Rushed", participle: "Rushed", esPres: "Apurarse / Correr con prisa", esPast: "Se apuró", esPart: "Apurado" },
  { type: "regular", sound: "d", base: "Wander", past: "Wandered", participle: "Wandered", esPres: "Vagar / Deambular", esPast: "Vagó / Deambuló", esPart: "Vagado / Deambulado" },
  { type: "regular", sound: "d", base: "Stroll", past: "Strolled", participle: "Strolled", esPres: "Pasear", esPast: "Paseó", esPart: "Paseado" },
  { type: "regular", sound: "t", base: "Hike", past: "Hiked", participle: "Hiked", esPres: "Hacer senderismo / Caminar", esPast: "Hizo senderismo", esPart: "Hecho senderismo" },
  { type: "regular", sound: "d", base: "Crawl", past: "Crawled", participle: "Crawled", esPres: "Gatear / Arrastrarse", esPast: "Gateó / Se arrastró", esPart: "Gateado / Arrastrado" },
  { type: "regular", sound: "t", base: "March", past: "Marched", participle: "Marched", esPres: "Marchar", esPast: "Marchó", esPart: "Marchado" },
  { type: "regular", sound: "d", base: "Stumble", past: "Stumbled", participle: "Stumbled", esPres: "Tropezar", esPast: "Tropezó", esPart: "Tropezado" },
  { type: "regular", sound: "t", base: "Trip", past: "Tripped", participle: "Tripped", esPres: "Tropezar / Hacer tropezar", esPast: "Tropezó", esPart: "Tropezado" },
  { type: "regular", sound: "t", base: "Slip", past: "Slipped", participle: "Slipped", esPres: "Resbalar", esPast: "Resbaló", esPart: "Resbalado" },
  { type: "regular", sound: "id", base: "Fold", past: "Folded", participle: "Folded", esPres: "Doblar", esPast: "Dobló", esPart: "Doblado" },
  { type: "regular", sound: "t", base: "Mop", past: "Mopped", participle: "Mopped", esPres: "Trapear", esPast: "Trapeó", esPart: "Trapeado" },
  { type: "regular", sound: "d", base: "Scrub", past: "Scrubbed", participle: "Scrubbed", esPres: "Fregar / Restregar", esPast: "Fregó / Restregó", esPart: "Fregado / Restregado" },
  { type: "regular", sound: "t", base: "Rinse", past: "Rinsed", participle: "Rinsed", esPres: "Enjuagar", esPast: "Enjuagó", esPart: "Enjuagado" },
  { type: "regular", sound: "t", base: "Wipe", past: "Wiped", participle: "Wiped", esPres: "Limpiar (con un trapo)", esPast: "Limpió", esPart: "Limpiado" },
  { type: "regular", sound: "d", base: "Tidy", past: "Tidied", participle: "Tidied", esPres: "Ordenar", esPast: "Ordenó", esPart: "Ordenado" },
  { type: "regular", sound: "id", base: "Doubt", past: "Doubted", participle: "Doubted", esPres: "Dudar", esPast: "Dudó", esPart: "Dudado" },
  { type: "regular", sound: "t", base: "Hope", past: "Hoped", participle: "Hoped", esPres: "Esperar (con esperanza)", esPast: "Esperó", esPart: "Esperado" },
  { type: "regular", sound: "d", base: "Fear", past: "Feared", participle: "Feared", esPres: "Temer", esPast: "Temió", esPart: "Temido" },
  { type: "regular", sound: "d", base: "Admire", past: "Admired", participle: "Admired", esPres: "Admirar", esPast: "Admiró", esPart: "Admirado" },
  { type: "regular", sound: "id", base: "Respect", past: "Respected", participle: "Respected", esPres: "Respetar", esPast: "Respetó", esPart: "Respetado" },
  { type: "regular", sound: "id", base: "Appreciate", past: "Appreciated", participle: "Appreciated", esPres: "Apreciar", esPast: "Apreció", esPart: "Apreciado" },
  { type: "regular", sound: "d", base: "Envy", past: "Envied", participle: "Envied", esPres: "Envidiar", esPast: "Envidió", esPart: "Envidiado" },
  { type: "regular", sound: "id", base: "Regret", past: "Regretted", participle: "Regretted", esPres: "Arrepentirse / Lamentar", esPast: "Se arrepintió / Lamentó", esPart: "Arrepentido / Lamentado" },
  { type: "regular", sound: "d", base: "Blame", past: "Blamed", participle: "Blamed", esPres: "Culpar", esPast: "Culpó", esPart: "Culpado" },
  { type: "regular", sound: "d", base: "Praise", past: "Praised", participle: "Praised", esPres: "Elogiar / Alabar", esPast: "Elogió / Alabó", esPart: "Elogiado / Alabado" },
  { type: "regular", sound: "d", base: "Criticize", past: "Criticized", participle: "Criticized", esPres: "Criticar", esPast: "Criticó", esPart: "Criticado" },
  { type: "regular", sound: "d", base: "Warn", past: "Warned", participle: "Warned", esPres: "Advertir", esPast: "Advirtió", esPart: "Advertido" },
  { type: "regular", sound: "d", base: "Advise", past: "Advised", participle: "Advised", esPres: "Aconsejar", esPast: "Aconsejó", esPart: "Aconsejado" },
  { type: "regular", sound: "id", base: "Persuade", past: "Persuaded", participle: "Persuaded", esPres: "Persuadir", esPast: "Persuadió", esPart: "Persuadido" },
  { type: "regular", sound: "d", base: "Discourage", past: "Discouraged", participle: "Discouraged", esPres: "Desanimar / Desalentar", esPast: "Desanimó / Desalentó", esPart: "Desanimado / Desalentado" },
  { type: "regular", sound: "id", base: "Motivate", past: "Motivated", participle: "Motivated", esPres: "Motivar", esPast: "Motivó", esPart: "Motivado" },
  { type: "regular", sound: "d", base: "Inspire", past: "Inspired", participle: "Inspired", esPres: "Inspirar", esPast: "Inspiró", esPart: "Inspirado" },
  { type: "irregular", base: "Oversleep", past: "Overslept", participle: "Overslept", esPres: "Quedarse dormido / Levantarse tarde", esPast: "Se quedó dormido", esPart: "Quedado dormido" },
  { type: "regular", sound: "d", base: "Yawn", past: "Yawned", participle: "Yawned", esPres: "Bostezar", esPast: "Bostezó", esPart: "Bostezado" },
  { type: "regular", sound: "d", base: "Doze", past: "Dozed", participle: "Dozed", esPres: "Dormitar", esPast: "Dormitó", esPart: "Dormitado" },
  { type: "regular", sound: "t", base: "Nap", past: "Napped", participle: "Napped", esPres: "Tomar una siesta", esPast: "Tomó una siesta", esPart: "Tomado una siesta" },
  { type: "regular", sound: "d", base: "Snore", past: "Snored", participle: "Snored", esPres: "Roncar", esPast: "Roncó", esPart: "Roncado" },
];
