// ─────────────────────────────────────────────────────────────────
// VERBS_EXTRA — verbos adicionales para el Diccionario de Verbos
// Este archivo se carga junto a index.html y se fusiona con VERBS,
// evitando duplicados automáticamente (ver script principal).
// Agrega aquí más verbos cuando quieras — mismo formato que index.html.
// ─────────────────────────────────────────────────────────────────
const VERBS_EXTRA = [

  // ─── IRREGULARES QUE FALTABAN ─────────────────────────────────
  { type: "irregular", base: "Shave", past: "Shaved", participle: "Shaved / Shaven", esPres: "Afeitar / Rasurar", esPast: "Afeitó / Rasuró", esPart: "Afeitado / Rasurado" },
  { type: "irregular", base: "Slit", past: "Slit", participle: "Slit", esPres: "Cortar / Hacer una raja", esPast: "Cortó / Hizo una raja", esPart: "Cortado" },
  { type: "irregular", base: "Bust", past: "Bust / Busted", participle: "Bust / Busted", esPres: "Reventar / Arrestar (informal)", esPast: "Reventó / Arrestó", esPart: "Reventado / Arrestado" },
  { type: "irregular", base: "Forecast", past: "Forecast", participle: "Forecast", esPres: "Pronosticar", esPast: "Pronosticó", esPart: "Pronosticado" },
  { type: "irregular", base: "Beseech", past: "Besought", participle: "Besought", esPres: "Suplicar / Rogar", esPast: "Suplicó / Rogó", esPart: "Suplicado / Rogado" },
  { type: "irregular", base: "Clothe", past: "Clad / Clothed", participle: "Clad / Clothed", esPres: "Vestir", esPast: "Vistió", esPart: "Vestido" },
  { type: "irregular", base: "Dwell", past: "Dwelt", participle: "Dwelt", esPres: "Habitar / Residir", esPast: "Habitó / Residió", esPart: "Habitado / Residido" },
  { type: "irregular", base: "Gird", past: "Girt", participle: "Girt", esPres: "Ceñir / Rodear", esPast: "Ciñó / Rodeó", esPart: "Ceñido / Rodeado" },
  { type: "irregular", base: "Grave", past: "Graved", participle: "Graven", esPres: "Grabar (en madera/piedra)", esPast: "Grabó", esPart: "Grabado" },
  { type: "irregular", base: "Lade", past: "Laded", participle: "Laden", esPres: "Cargar", esPast: "Cargó", esPart: "Cargado" },
  { type: "irregular", base: "Mow", past: "Mowed", participle: "Mown", esPres: "Segar / Cortar césped", esPast: "Segó / Cortó césped", esPart: "Segado / Cortado césped" },
  { type: "irregular", base: "Rive", past: "Rived", participle: "Riven", esPres: "Partir / Hendir", esPast: "Partió / Hendix", esPart: "Partido / Hendido" },
  { type: "irregular", base: "Sew", past: "Sewed", participle: "Sewn", esPres: "Coser", esPast: "Cosió", esPart: "Cosido" },
  { type: "irregular", base: "Shear", past: "Sheared", participle: "Shorn", esPres: "Esquilar", esPast: "Esquiló", esPart: "Esquilado" },
  { type: "irregular", base: "Show", past: "Showed", participle: "Shown", esPres: "Mostrar", esPast: "Mostró", esPart: "Mostrado" },
  { type: "irregular", base: "Sow", past: "Sowed", participle: "Sown", esPres: "Sembrar", esPast: "Sembró", esPart: "Sembrado" },
  { type: "irregular", base: "Strew", past: "Strewed", participle: "Strewn", esPres: "Esparcir / Desparramar", esPast: "Esparció / Desparramó", esPart: "Esparcido / Desparramado" },
  { type: "irregular", base: "Swear", past: "Swore", participle: "Sworn", esPres: "Jurar", esPast: "Juró", esPart: "Jurado" },
  { type: "irregular", base: "Tear", past: "Tore", participle: "Torn", esPres: "Rasgar / Romper", esPast: "Rasgó / Rompió", esPart: "Rasgado / Roto" },
  { type: "irregular", base: "Tread", past: "Trod", participle: "Trodden", esPres: "Pisar / Andar", esPast: "Pisó / Anduvo", esPart: "Pisado / Andado" },
  { type: "irregular", base: "Weave", past: "Wove", participle: "Woven", esPres: "Tejer", esPast: "Tejió", esPart: "Tejido" },
  { type: "irregular", base: "Wind", past: "Wound", participle: "Wound", esPres: "Enrollar / Dar cuerda", esPast: "Enrolló / Dio cuerda", esPart: "Enrollado / Dado cuerda" },

  // ─── TECNOLOGÍA Y REDES SOCIALES ───────────────────────────────
  { type: "regular", sound: "d", base: "Design", past: "Designed", participle: "Designed", esPres: "Diseñar", esPast: "Diseñó", esPart: "Diseñado" },
  { type: "regular", sound: "d", base: "Install", past: "Installed", participle: "Installed", esPres: "Instalar", esPast: "Instaló", esPart: "Instalado" },
  { type: "regular", sound: "id", base: "Disconnect", past: "Disconnected", participle: "Disconnected", esPres: "Desconectar", esPast: "Desconectó", esPart: "Desconectado" },
  { type: "regular", sound: "d", base: "Plug", past: "Plugged", participle: "Plugged", esPres: "Enchufar", esPast: "Enchufó", esPart: "Enchufado" },
  { type: "regular", sound: "d", base: "Unplug", past: "Unplugged", participle: "Unplugged", esPres: "Desenchufar", esPast: "Desenchufó", esPart: "Desenchufado" },
  { type: "regular", sound: "d", base: "Charge", past: "Charged", participle: "Charged", esPres: "Cargar", esPast: "Cargó", esPart: "Cargado" },
  { type: "regular", sound: "id", base: "Delete", past: "Deleted", participle: "Deleted", esPres: "Eliminar / Borrar", esPast: "Eliminó / Borró", esPart: "Eliminado / Borrado" },
  { type: "regular", sound: "d", base: "Scan", past: "Scanned", participle: "Scanned", esPres: "Escanear", esPast: "Escaneó", esPart: "Escaneado" },
  { type: "regular", sound: "id", base: "Paste", past: "Pasted", participle: "Pasted", esPres: "Pegar", esPast: "Pegó", esPart: "Pegado" },
  { type: "regular", sound: "t", base: "Click", past: "Clicked", participle: "Clicked", esPres: "Hacer clic", esPast: "Hizo clic", esPart: "Hecho clic" },
  { type: "regular", sound: "t", base: "Tap", past: "Tapped", participle: "Tapped", esPres: "Tocar / Pulsar", esPast: "Tocó / Pulsó", esPart: "Tocado / Pulsado" },
  { type: "regular", sound: "t", base: "Swipe", past: "Swiped", participle: "Swiped", esPres: "Deslizar", esPast: "Deslizó", esPart: "Deslizado" },
  { type: "regular", sound: "d", base: "Browse", past: "Browsed", participle: "Browsed", esPres: "Navegar / Explorar", esPast: "Navegó / Exploró", esPart: "Navegado / Explorado" },
  { type: "regular", sound: "id", base: "Chat", past: "Chatted", participle: "Chatted", esPres: "Chatear / Conversar", esPast: "Chateó / Conversó", esPart: "Chateado / Conversado" },
  { type: "regular", sound: "id", base: "Text", past: "Texted", participle: "Texted", esPres: "Enviar un mensaje de texto", esPast: "Envió un mensaje de texto", esPart: "Enviado un mensaje de texto" },
  { type: "regular", sound: "d", base: "Phone", past: "Phoned", participle: "Phoned", esPres: "Llamar por teléfono", esPast: "Llamó por teléfono", esPart: "Llamado por teléfono" },
  { type: "regular", sound: "d", base: "Email", past: "Emailed", participle: "Emailed", esPres: "Enviar un correo", esPast: "Envió un correo", esPart: "Enviado un correo" },
  { type: "regular", sound: "id", base: "Post", past: "Posted", participle: "Posted", esPres: "Publicar", esPast: "Publicó", esPart: "Publicado" },
  { type: "regular", sound: "d", base: "Share", past: "Shared", participle: "Shared", esPres: "Compartir", esPast: "Compartió", esPart: "Compartido" },
  { type: "regular", sound: "d", base: "Subscribe", past: "Subscribed", participle: "Subscribed", esPres: "Suscribirse", esPast: "Se suscribió", esPart: "Suscrito" },
  { type: "regular", sound: "d", base: "Unfollow", past: "Unfollowed", participle: "Unfollowed", esPres: "Dejar de seguir", esPast: "Dejó de seguir", esPart: "Dejado de seguir" },
  { type: "regular", sound: "t", base: "Block", past: "Blocked", participle: "Blocked", esPres: "Bloquear", esPast: "Bloqueó", esPart: "Bloqueado" },
  { type: "regular", sound: "id", base: "Mute", past: "Muted", participle: "Muted", esPres: "Silenciar", esPast: "Silenció", esPart: "Silenciado" },
  { type: "regular", sound: "id", base: "Record", past: "Recorded", participle: "Recorded", esPres: "Grabar", esPast: "Grabó", esPart: "Grabado" },
  { type: "regular", sound: "d", base: "Film", past: "Filmed", participle: "Filmed", esPres: "Filmar", esPast: "Filmó", esPart: "Filmado" },
  { type: "regular", sound: "d", base: "Stream", past: "Streamed", participle: "Streamed", esPres: "Transmitir en vivo", esPast: "Transmitió en vivo", esPart: "Transmitido en vivo" },
  { type: "regular", sound: "t", base: "Publish", past: "Published", participle: "Published", esPres: "Publicar", esPast: "Publicó", esPart: "Publicado" },
  { type: "regular", sound: "id", base: "Translate", past: "Translated", participle: "Translated", esPres: "Traducir", esPast: "Tradujo", esPart: "Traducido" },
  { type: "regular", sound: "t", base: "Pronounce", past: "Pronounced", participle: "Pronounced", esPres: "Pronunciar", esPast: "Pronunció", esPart: "Pronunciado" },
  { type: "regular", sound: "d", base: "Upload", past: "Uploaded", participle: "Uploaded", esPres: "Subir (archivos)", esPast: "Subió", esPart: "Subido" },
  { type: "regular", sound: "d", base: "Download", past: "Downloaded", participle: "Downloaded", esPres: "Descargar", esPast: "Descargó", esPart: "Descargado" },
  { type: "regular", sound: "t", base: "Screenshot", past: "Screenshotted", participle: "Screenshotted", esPres: "Capturar pantalla", esPast: "Capturó pantalla", esPart: "Capturado pantalla" },
  { type: "regular", sound: "d", base: "Zoom", past: "Zoomed", participle: "Zoomed", esPres: "Hacer zoom / Ampliar", esPast: "Hizo zoom", esPart: "Hecho zoom" },
  { type: "regular", sound: "d", base: "Drag", past: "Dragged", participle: "Dragged", esPres: "Arrastrar", esPast: "Arrastró", esPart: "Arrastrado" },
  { type: "regular", sound: "d", base: "Drop", past: "Dropped", participle: "Dropped", esPres: "Soltar / Arrastrar y soltar", esPast: "Soltó", esPart: "Soltado" },
  { type: "regular", sound: "d", base: "Login", past: "Logged in", participle: "Logged in", esPres: "Iniciar sesión", esPast: "Inició sesión", esPart: "Iniciado sesión" },
  { type: "regular", sound: "d", base: "Logout", past: "Logged out", participle: "Logged out", esPres: "Cerrar sesión", esPast: "Cerró sesión", esPart: "Cerrado sesión" },
  { type: "regular", sound: "d", base: "Register", past: "Registered", participle: "Registered", esPres: "Registrarse", esPast: "Se registró", esPart: "Registrado" },
  { type: "regular", sound: "d", base: "Verify", past: "Verified", participle: "Verified", esPres: "Verificar", esPast: "Verificó", esPart: "Verificado" },
  { type: "regular", sound: "d", base: "Authenticate", past: "Authenticated", participle: "Authenticated", esPres: "Autenticar", esPast: "Autenticó", esPart: "Autenticado" },

  // ─── CASA Y RUTINA DIARIA ───────────────────────────────────────
  { type: "regular", sound: "t", base: "Watch", past: "Watched", participle: "Watched", esPres: "Mirar / Observar", esPast: "Miró / Observó", esPart: "Mirado / Observado" },
  { type: "regular", sound: "t", base: "Brush", past: "Brushed", participle: "Brushed", esPres: "Cepillar", esPast: "Cepilló", esPart: "Cepillado" },
  { type: "regular", sound: "d", base: "Comb", past: "Combed", participle: "Combed", esPres: "Peinar", esPast: "Peinó", esPart: "Peinado" },
  { type: "regular", sound: "d", base: "Iron", past: "Ironed", participle: "Ironed", esPres: "Planchar", esPast: "Planchó", esPart: "Planchado" },
  { type: "regular", sound: "d", base: "Vacuum", past: "Vacuumed", participle: "Vacuumed", esPres: "Aspirar", esPast: "Aspiró", esPart: "Aspirado" },
  { type: "regular", sound: "id", base: "Dust", past: "Dusted", participle: "Dusted", esPres: "Quitar el polvo", esPast: "Quitó el polvo", esPart: "Quitado el polvo" },
  { type: "regular", sound: "d", base: "Water", past: "Watered", participle: "Watered", esPres: "Regar", esPast: "Regó", esPart: "Regado" },
  { type: "regular", sound: "id", base: "Paint", past: "Painted", participle: "Painted", esPres: "Pintar", esPast: "Pintó", esPart: "Pintado" },
  { type: "regular", sound: "d", base: "Relax", past: "Relaxed", participle: "Relaxed", esPres: "Relajarse", esPast: "Se relajó", esPart: "Relajado" },
  { type: "regular", sound: "id", base: "Rest", past: "Rested", participle: "Rested", esPres: "Descansar", esPast: "Descansó", esPart: "Descansado" },
  { type: "regular", sound: "d", base: "Breathe", past: "Breathed", participle: "Breathed", esPres: "Respirar", esPast: "Respiró", esPart: "Respirado" },
  { type: "regular", sound: "d", base: "Stretch", past: "Stretched", participle: "Stretched", esPres: "Estirarse", esPast: "Se estiró", esPart: "Estirado" },
  { type: "regular", sound: "d", base: "Jog", past: "Jogged", participle: "Jogged", esPres: "Trotar", esPast: "Trotó", esPart: "Trotado" },
  { type: "regular", sound: "t", base: "Skip", past: "Skipped", participle: "Skipped", esPres: "Saltar / Saltarse", esPast: "Saltó / Se saltó", esPart: "Saltado" },
  { type: "regular", sound: "t", base: "Dress", past: "Dressed", participle: "Dressed", esPres: "Vestirse", esPast: "Se vistió", esPart: "Vestido" },
  { type: "regular", sound: "d", base: "Undress", past: "Undressed", participle: "Undressed", esPres: "Desvestirse", esPast: "Se desvistió", esPart: "Desvestido" },
  { type: "regular", sound: "d", base: "Shower", past: "Showered", participle: "Showered", esPres: "Ducharse", esPast: "Se duchó", esPart: "Duchado" },
  { type: "regular", sound: "t", base: "Bathe", past: "Bathed", participle: "Bathed", esPres: "Bañarse", esPast: "Se bañó", esPart: "Bañado" },
  { type: "regular", sound: "t", base: "Wash", past: "Washed", participle: "Washed", esPres: "Lavar", esPast: "Lavó", esPart: "Lavado" },
  { type: "regular", sound: "d", base: "Clean", past: "Cleaned", participle: "Cleaned", esPres: "Limpiar", esPast: "Limpió", esPart: "Limpiado" },
  { type: "regular", sound: "d", base: "Sweep", past: "Swept", participle: "Swept", esPres: "Barrer", esPast: "Barrió", esPart: "Barrido" },
  { type: "regular", sound: "d", base: "Cook", past: "Cooked", participle: "Cooked", esPres: "Cocinar", esPast: "Cocinó", esPart: "Cocinado" },
  { type: "regular", sound: "t", base: "Heat", past: "Heated", participle: "Heated", esPres: "Calentar", esPast: "Calentó", esPart: "Calentado" },
  { type: "regular", sound: "d", base: "Microwave", past: "Microwaved", participle: "Microwaved", esPres: "Calentar en microondas", esPast: "Calentó en microondas", esPart: "Calentado en microondas" },
  { type: "regular", sound: "t", base: "Freeze", past: "Froze", participle: "Frozen", esPres: "Congelar", esPast: "Congeló", esPart: "Congelado" },
  { type: "regular", sound: "t", base: "Thaw", past: "Thawed", participle: "Thawed", esPres: "Descongelar", esPast: "Descongeló", esPart: "Descongelado" },

  // ─── EMOCIONES Y COMUNICACIÓN ───────────────────────────────────
  { type: "regular", sound: "t", base: "Laugh", past: "Laughed", participle: "Laughed", esPres: "Reír", esPast: "Rio", esPart: "Reído" },
  { type: "regular", sound: "d", base: "Cry", past: "Cried", participle: "Cried", esPres: "Llorar", esPast: "Lloró", esPart: "Llorado" },
  { type: "regular", sound: "d", base: "Smile", past: "Smiled", participle: "Smiled", esPres: "Sonreír", esPast: "Sonrió", esPart: "Sonreído" },
  { type: "regular", sound: "id", base: "Shout", past: "Shouted", participle: "Shouted", esPres: "Gritar", esPast: "Gritó", esPart: "Gritado" },
  { type: "regular", sound: "d", base: "Whisper", past: "Whispered", participle: "Whispered", esPres: "Susurrar", esPast: "Susurró", esPart: "Susurrado" },
  { type: "regular", sound: "d", base: "Scream", past: "Screamed", participle: "Screamed", esPres: "Chillar / Gritar", esPast: "Chilló / Gritó", esPart: "Chillado / Gritado" },
  { type: "regular", sound: "d", base: "Agree", past: "Agreed", participle: "Agreed", esPres: "Estar de acuerdo / Acordar", esPast: "Estuvo de acuerdo / Acordó", esPart: "Acordado" },
  { type: "regular", sound: "d", base: "Disagree", past: "Disagreed", participle: "Disagreed", esPres: "Discrepar / No estar de acuerdo", esPast: "Discrepó / No estuvo de acuerdo", esPart: "Discrepado" },
  { type: "regular", sound: "d", base: "Argue", past: "Argued", participle: "Argued", esPres: "Discutir / Argumentar", esPast: "Discutió / Argumentó", esPart: "Discutido / Argumentado" },
  { type: "regular", sound: "d", base: "Complain", past: "Complained", participle: "Complained", esPres: "Quejarse", esPast: "Se quejó", esPart: "Quejado" },
  { type: "regular", sound: "d", base: "Apologize", past: "Apologized", participle: "Apologized", esPres: "Disculparse / Pedir perdón", esPast: "Se disculpó / Pidió perdón", esPart: "Disculpado" },
  { type: "regular", sound: "t", base: "Thank", past: "Thanked", participle: "Thanked", esPres: "Agradecer", esPast: "Agradeció", esPart: "Agradecido" },
  { type: "regular", sound: "id", base: "Congratulate", past: "Congratulated", participle: "Congratulated", esPres: "Felicitar", esPast: "Felicitó", esPart: "Felicitado" },
  { type: "regular", sound: "id", base: "Celebrate", past: "Celebrated", participle: "Celebrated", esPres: "Celebrar", esPast: "Celebró", esPart: "Celebrado" },
  { type: "regular", sound: "d", base: "Hug", past: "Hugged", participle: "Hugged", esPres: "Abrazar", esPast: "Abrazó", esPart: "Abrazado" },
  { type: "regular", sound: "t", base: "Kiss", past: "Kissed", participle: "Kissed", esPres: "Besas", esPast: "Besó", esPart: "Besado" },
  { type: "regular", sound: "t", base: "Miss", past: "Missed", participle: "Missed", esPres: "Extrañar / Perder", esPast: "Extrañó / Perdió", esPart: "Extrañado / Perdido" },

  // ─── ESCUELA Y TRABAJO ──────────────────────────────────────────
  { type: "regular", sound: "d", base: "Memorize", past: "Memorized", participle: "Memorized", esPres: "Memorizar", esPast: "Memorizó", esPart: "Memorizado" },
  { type: "regular", sound: "d", base: "Revise", past: "Revised", participle: "Revised", esPres: "Revisar / Corregir", esPast: "Revisó / Corrigió", esPart: "Revisado / Corregido" },
  { type: "regular", sound: "d", base: "Summarize", past: "Summarized", participle: "Summarized", esPres: "Resumir", esPast: "Resumió", esPart: "Resumido" },
  { type: "regular", sound: "id", base: "Highlight", past: "Highlighted", participle: "Highlighted", esPres: "Resaltar / Subrayar", esPast: "Resaltó / Subrayó", esPart: "Resaltado / Subrayado" },
  { type: "regular", sound: "d", base: "Underline", past: "Underlined", participle: "Underlined", esPres: "Subrayar", esPast: "Subrayó", esPart: "Subrayado" },
  { type: "regular", sound: "d", base: "Circle", past: "Circled", participle: "Circled", esPres: "Encerrar en un círculo", esPast: "Encerró en un círculo", esPart: "Encerrado en un círculo" },
  { type: "regular", sound: "id", base: "Grade", past: "Graded", participle: "Graded", esPres: "Calificar", esPast: "Calificó", esPart: "Calificado" },
  { type: "regular", sound: "d", base: "Score", past: "Scored", participle: "Scored", esPres: "Anotar / Marcar un punto", esPast: "Anotó / Marcó un punto", esPart: "Anotado / Marcado" },
  { type: "regular", sound: "t", base: "Pass", past: "Passed", participle: "Passed", esPres: "Aprobar / Pasar", esPast: "Aprobó / Pasó", esPart: "Aprobado / Pasado" },
  { type: "regular", sound: "id", base: "Graduate", past: "Graduated", participle: "Graduated", esPres: "Graduarse", esPast: "Se graduó", esPart: "Graduado" },
  { type: "regular", sound: "d", base: "Enroll", past: "Enrolled", participle: "Enrolled", esPres: "Inscribirse / Matricularse", esPast: "Se inscribió / Se matriculó", esPart: "Inscrito / Matriculado" },
  { type: "regular", sound: "d", base: "Interview", past: "Interviewed", participle: "Interviewed", esPres: "Entrevistar", esPast: "Entrevistó", esPart: "Entrevistado" },
  { type: "regular", sound: "d", base: "Fire", past: "Fired", participle: "Fired", esPres: "Despedir", esPast: "Despidió", esPart: "Despedido" },
  { type: "regular", sound: "id", base: "Promote", past: "Promoted", participle: "Promoted", esPres: "Ascender / Promover", esPast: "Ascendió / Promovió", esPart: "Ascendido / Promovido" },
  { type: "regular", sound: "d", base: "Retire", past: "Retired", participle: "Retired", esPres: "Jubilarse / Retirarse", esPast: "Se jubiló / Se retiró", esPart: "Jubilado / Retirado" },
  { type: "regular", sound: "d", base: "Resign", past: "Resigned", participle: "Resigned", esPres: "Renunciar / Dimitir", esPast: "Renunció / Dimitió", esPart: "Renunciado / Dimitido" },
  { type: "regular", sound: "id", base: "Negotiate", past: "Negotiated", participle: "Negotiated", esPres: "Negociar", esPast: "Negoció", esPart: "Negociado" },
  { type: "regular", sound: "d", base: "Sign", past: "Signed", participle: "Signed", esPres: "Firmar", esPast: "Firmó", esPart: "Firmado" },
  { type: "regular", sound: "d", base: "Define", past: "Defined", participle: "Defined", esPres: "Definir", esPast: "Definió", esPart: "Definido" },
  { type: "regular", sound: "d", base: "Analyze", past: "Analyzed", participle: "Analyzed", esPres: "Analizar", esPast: "Analizó", esPart: "Analizado" },
  { type: "regular", sound: "id", base: "Contrast", past: "Contrasted", participle: "Contrasted", esPres: "Contrastar", esPast: "Contrastó", esPart: "Contrastado" },
  { type: "regular", sound: "id", base: "Debate", past: "Debated", participle: "Debated", esPres: "Debatir", esPast: "Debatió", esPart: "Debatido" },
  { type: "regular", sound: "t", base: "Research", past: "Researched", participle: "Researched", esPres: "Investigar", esPast: "Investigó", esPart: "Investigado" },
  { type: "regular", sound: "id", base: "Investigate", past: "Investigated", participle: "Investigated", esPres: "Investigar", esPast: "Investigó", esPart: "Investigado" },
  { type: "regular", sound: "d", base: "Observe", past: "Observed", participle: "Observed", esPres: "Observar", esPast: "Observó", esPart: "Observado" },
  { type: "regular", sound: "id", base: "Experiment", past: "Experimented", participle: "Experimented", esPres: "Experimentar", esPast: "Experimentó", esPart: "Experimentado" },
  { type: "regular", sound: "id", base: "Conclude", past: "Concluded", participle: "Concluded", esPres: "Concluir", esPast: "Concluyó", esPart: "Concluido" },
  { type: "regular", sound: "id", base: "Calculate", past: "Calculated", participle: "Calculated", esPres: "Calcular", esPast: "Calculó", esPart: "Calculado" },
  { type: "regular", sound: "d", base: "Weigh", past: "Weighed", participle: "Weighed", esPres: "Pesar", esPast: "Pesó", esPart: "Pesado" },
  { type: "regular", sound: "id", base: "Estimate", past: "Estimated", participle: "Estimated", esPres: "Estimar / Calcular", esPast: "Estimó / Calculó", esPart: "Estimado / Calculado" },
 