// ─────────────────────────────────────────────────────────────────
// VERBS_EXTRA — verbos adicionales para el Diccionario de Verbos
// Este archivo se carga junto a index.html y se fusiona con VERBS,
// evitando duplicados automáticamente (ver script principal).
// Agrega aquí más verbos cuando quieras — mismo formato que index.html.
// ─────────────────────────────────────────────────────────────────
const VERBS_EXTRA = [

  // ─── IRREGULARES QUE FALTABAN ─────────────────────────────────
  { type: "irregular", base: "Shave", past: "Shaved", participle: "Shaved / Shaven", esPres: "Afeitar / Rasurar", esPast: "Afeitó / Rasuró", esPart: "Afeitado / Rasurado" },
  { type: "irregular", base: "Slit", past: "Slit", participle: "Slit", esPres: "Cortar / Hacer una raja", esPast: "Cortó / Hizo una raja", esPart: "Cortado" },
  { type: "irregular", base: "Bust", past: "Bust / Busted", participle: "Bust / Busted", esPres: "Reventar / Arrestar (informal)", esPast: "Reventó / Arrestó", esPart: "Reventado / Arrestado" },
  { type: "irregular", base: "Forecast", past: "Forecast", participle: "Forecast", esPres: "Pronosticar", esPast: "Pronosticó", esPart: "Pronosticado" },

  // ─── TECNOLOGÍA Y REDES SOCIALES ───────────────────────────────
  { type: "regular", sound: "d", base: "Design", past: "Designed", participle: "Designed", esPres: "Diseñar", esPast: "Diseñó", esPart: "Diseñado" },
  { type: "regular", sound: "d", base: "Install", past: "Installed", participle: "Installed", esPres: "Instalar", esPast: "Instaló", esPart: "Instalado" },
  { type: "regular", sound: "id", base: "Disconnect", past: "Disconnected", participle: "Disconnected", esPres: "Desconectar", esPast: "Desconectó", esPart: "Desconectado" },
  { type: "regular", sound: "d", base: "Plug", past: "Plugged", participle: "Plugged", esPres: "Enchufar", esPast: "Enchufó", esPart: "Enchufado" },
  { type: "regular", sound: "d", base: "Unplug", past: "Unplugged", participle: "Unplugged", esPres: "Desenchufar", esPast: "Desenchufó", esPart: "Desenchufado" },
  { type: "regular", sound: "d", base: "Charge", past: "Charged", participle: "Charged", esPres: "Cargar", esPast: "Cargó", esPart: "Cargado" },
  { type: "regular", sound: "id", base: "Delete", past: "Deleted", participle: "Deleted", esPres: "Eliminar / Borrar", esPast: "Eliminó / Borró", esPart: "Eliminado / Borrado" },
  { type: "regular", sound: "d", base: "Scan", past: "Scanned", participle: "Scanned", esPres: "Escanear", esPast: "Escaneó", esPart: "Escaneado" },
  { type: "regular", sound: "id", base: "Paste", past: "Pasted", participle: "Pasted", esPres: "Pegar", esPast: "Pegó", esPart: "Pegado" },
  { type: "regular", sound: "t", base: "Click", past: "Clicked", participle: "Clicked", esPres: "Hacer clic", esPast: "Hizo clic", esPart: "Hecho clic" },
  { type: "regular", sound: "t", base: "Tap", past: "Tapped", participle: "Tapped", esPres: "Tocar / Pulsar", esPast: "Tocó / Pulsó", esPart: "Tocado / Pulsado" },
  { type: "regular", sound: "t", base: "Swipe", past: "Swiped", participle: "Swiped", esPres: "Deslizar", esPast: "Deslizó", esPart: "Deslizado" },
  { type: "regular", sound: "d", base: "Browse", past: "Browsed", participle: "Browsed", esPres: "Navegar / Explorar", esPast: "Navegó / Exploró", esPart: "Navegado / Explorado" },
  { type: "regular", sound: "id", base: "Chat", past: "Chatted", participle: "Chatted", esPres: "Chatear / Conversar", esPast: "Chateó / Conversó", esPart: "Chateado / Conversado" },
  { type: "regular", sound: "id", base: "Text", past: "Texted", participle: "Texted", esPres: "Enviar un mensaje de texto", esPast: "Envió un mensaje de texto", esPart: "Enviado un mensaje de texto" },
  { type: "regular", sound: "d", base: "Phone", past: "Phoned", participle: "Phoned", esPres: "Llamar por teléfono", esPast: "Llamó por teléfono", esPart: "Llamado por teléfono" },
  { type: "regular", sound: "d", base: "Email", past: "Emailed", participle: "Emailed", esPres: "Enviar un correo", esPast: "Envió un correo", esPart: "Enviado un correo" },
  { type: "regular", sound: "id", base: "Post", past: "Posted", participle: "Posted", esPres: "Publicar", esPast: "Publicó", esPart: "Publicado" },
  { type: "regular", sound: "d", base: "Share", past: "Shared", participle: "Shared", esPres: "Compartir", esPast: "Compartió", esPart: "Compartido" },
  { type: "regular", sound: "d", base: "Subscribe", past: "Subscribed", participle: "Subscribed", esPres: "Suscribirse", esPast: "Se suscribió", esPart: "Suscrito" },
  { type: "regular", sound: "d", base: "Unfollow", past: "Unfollowed", participle: "Unfollowed", esPres: "Dejar de seguir", esPast: "Dejó de seguir", esPart: "Dejado de seguir" },
  { type: "regular", sound: "t", base: "Block", past: "Blocked", participle: "Blocked", esPres: "Bloquear", esPast: "Bloqueó", esPart: "Bloqueado" },
  { type: "regular", sound: "id", base: "Mute", past: "Muted", participle: "Muted", esPres: "Silenciar", esPast: "Silenció", esPart: "Silenciado" },
  { type: "regular", sound: "id", base: "Record", past: "Recorded", participle: "Recorded", esPres: "Grabar", esPast: "Grabó", esPart: "Grabado" },
  { type: "regular", sound: "d", base: "Film", past: "Filmed", participle: "Filmed", esPres: "Filmar", esPast: "Filmó", esPart: "Filmado" },
  { type: "regular", sound: "d", base: "Stream", past: "Streamed", participle: "Streamed", esPres: "Transmitir en vivo", esPast: "Transmitió en vivo", esPart: "Transmitido en vivo" },
  { type: "regular", sound: "t", base: "Publish", past: "Published", participle: "Published", esPres: "Publicar", esPast: "Publicó", esPart: "Publicado" },
  { type: "regular", sound: "id", base: "Translate", past: "Translated", participle: "Translated", esPres: "Traducir", esPast: "Tradujo", esPart: "Traducido" },
  { type: "regular", sound: "t", base: "Pronounce", past: "Pronounced", participle: "Pronounced", esPres: "Pronunciar", esPast: "Pronunció", esPart: "Pronunciado" },

  // ─── CASA Y RUTINA DIARIA ───────────────────────────────────────
  { type: "regular", sound: "t", base: "Watch", past: "Watched", participle: "Watched", esPres: "Mirar / Observar", esPast: "Miró / Observó", esPart: "Mirado / Observado" },
  { type: "regular", sound: "t", base: "Brush", past: "Brushed", participle: "Brushed", esPres: "Cepillar", esPast: "Cepilló", esPart: "Cepillado" },
  { type: "regular", sound: "d", base: "Comb", past: "Combed", participle: "Combed", esPres: "Peinar", esPast: "Peinó", esPart: "Peinado" },
  { type: "regular", sound: "d", base: "Iron", past: "Ironed", participle: "Ironed", esPres: "Planchar", esPast: "Planchó", esPart: "Planchado" },
  { type: "regular", sound: "d", base: "Vacuum", past: "Vacuumed", participle: "Vacuumed", esPres: "Aspirar", esPast: "Aspiró", esPart: "Aspirado" },
  { type: "regular", sound: "id", base: "Dust", past: "Dusted", participle: "Dusted", esPres: "Quitar el polvo", esPast: "Quitó el polvo", esPart: "Quitado el polvo" },
  { type: "regular", sound: "d", base: "Water", past: "Watered", participle: "Watered", esPres: "Regar", esPast: "Regó", esPart: "Regado" },
  { type: "regular", sound: "id", base: "Paint", past: "Painted", participle: "Painted", esPres: "Pintar", esPast: "Pintó", esPart: "Pintado" },
  { type: "regular", sound: "d", base: "Relax", past: "Relaxed", participle: "Relaxed", esPres: "Relajarse", esPast: "Se relajó", esPart: "Relajado" },
  { type: "regular", sound: "id", base: "Rest", past: "Rested", participle: "Rested", esPres: "Descansar", esPast: "Descansó", esPart: "Descansado" },
  { type: "regular", sound: "d", base: "Breathe", past: "Breathed", participle: "Breathed", esPres: "Respirar", esPast: "Respiró", esPart: "Respirado" },
  { type: "regular", sound: "d", base: "Stretch", past: "Stretched", participle: "Stretched", esPres: "Estirarse", esPast: "Se estiró", esPart: "Estirado" },
  { type: "regular", sound: "d", base: "Jog", past: "Jogged", participle: "Jogged", esPres: "Trotar", esPast: "Trotó", esPart: "Trotado" },
  { type: "regular", sound: "t", base: "Skip", past: "Skipped", participle: "Skipped", esPres: "Saltar / Saltarse", esPast: "Saltó / Se saltó", esPart: "Saltado" },

  // ─── EMOCIONES Y COMUNICACIÓN ───────────────────────────────────
  { type: "regular", sound: "t", base: "Laugh", past: "Laughed", participle: "Laughed", esPres: "Reír", esPast: "Rio", esPart: "Reído" },
  { type: "regular", sound: "d", base: "Cry", past: "Cried", participle: "Cried", esPres: "Llorar", esPast: "Lloró", esPart: "Llorado" },
  { type: "regular", sound: "d", base: "Smile", past: "Smiled", participle: "Smiled", esPres: "Sonreír", esPast: "Sonrió", esPart: "Sonreído" },
  { type: "regular", sound: "id", base: "Shout", past: "Shouted", participle: "Shouted", esPres: "Gritar", esPast: "Gritó", esPart: "Gritado" },
  { type: "regular", sound: "d", base: "Whisper", past: "Whispered", participle: "Whispered", esPres: "Susurrar", esPast: "Susurró", esPart: "Susurrado" },
  { type: "regular", sound: "d", base: "Scream", past: "Screamed", participle: "Screamed", esPres: "Chillar / Gritar", esPast: "Chilló / Gritó", esPart: "Chillado / Gritado" },
  { type: "regular", sound: "d", base: "Agree", past: "Agreed", participle: "Agreed", esPres: "Estar de acuerdo / Acordar", esPast: "Estuvo de acuerdo / Acordó", esPart: "Acordado" },
  { type: "regular", sound: "d", base: "Disagree", past: "Disagreed", participle: "Disagreed", esPres: "Discrepar / No estar de acuerdo", esPast: "Discrepó / No estuvo de acuerdo", esPart: "Discrepado" },
  { type: "regular", sound: "d", base: "Argue", past: "Argued", participle: "Argued", esPres: "Discutir / Argumentar", esPast: "Discutió / Argumentó", esPart: "Discutido / Argumentado" },
  { type: "regular", sound: "d", base: "Complain", past: "Complained", participle: "Complained", esPres: "Quejarse", esPast: "Se quejó", esPart: "Quejado" },
  { type: "regular", sound: "d", base: "Apologize", past: "Apologized", participle: "Apologized", esPres: "Disculparse / Pedir perdón", esPast: "Se disculpó / Pidió perdón", esPart: "Disculpado" },
  { type: "regular", sound: "t", base: "Thank", past: "Thanked", participle: "Thanked", esPres: "Agradecer", esPast: "Agradeció", esPart: "Agradecido" },
  { type: "regular", sound: "id", base: "Congratulate", past: "Congratulated", participle: "Congratulated", esPres: "Felicitar", esPast: "Felicitó", esPart: "Felicitado" },
  { type: "regular", sound: "id", base: "Celebrate", past: "Celebrated", participle: "Celebrated", esPres: "Celebrar", esPast: "Celebró", esPart: "Celebrado" },

  // ─── ESCUELA Y TRABAJO ──────────────────────────────────────────
  { type: "regular", sound: "d", base: "Memorize", past: "Memorized", participle: "Memorized", esPres: "Memorizar", esPast: "Memorizó", esPart: "Memorizado" },
  { type: "regular", sound: "d", base: "Revise", past: "Revised", participle: "Revised", esPres: "Revisar / Corregir", esPast: "Revisó / Corrigió", esPart: "Revisado / Corregido" },
  { type: "regular", sound: "d", base: "Summarize", past: "Summarized", participle: "Summarized", esPres: "Resumir", esPast: "Resumió", esPart: "Resumido" },
  { type: "regular", sound: "id", base: "Highlight", past: "Highlighted", participle: "Highlighted", esPres: "Resaltar / Subrayar", esPast: "Resaltó / Subrayó", esPart: "Resaltado / Subrayado" },
  { type: "regular", sound: "d", base: "Underline", past: "Underlined", participle: "Underlined", esPres: "Subrayar", esPast: "Subrayó", esPart: "Subrayado" },
  { type: "regular", sound: "d", base: "Circle", past: "Circled", participle: "Circled", esPres: "Encerrar en un círculo", esPast: "Encerró en un círculo", esPart: "Encerrado en un círculo" },
  { type: "regular", sound: "id", base: "Grade", past: "Graded", participle: "Graded", esPres: "Calificar", esPast: "Calificó", esPart: "Calificado" },
  { type: "regular", sound: "d", base: "Score", past: "Scored", participle: "Scored", esPres: "Anotar / Marcar un punto", esPast: "Anotó / Marcó un punto", esPart: "Anotado / Marcado" },
  { type: "regular", sound: "t", base: "Pass", past: "Passed", participle: "Passed", esPres: "Aprobar / Pasar", esPast: "Aprobó / Pasó", esPart: "Aprobado / Pasado" },
  { type: "regular", sound: "id", base: "Graduate", past: "Graduated", participle: "Graduated", esPres: "Graduarse", esPast: "Se graduó", esPart: "Graduado" },
  { type: "regular", sound: "d", base: "Enroll", past: "Enrolled", participle: "Enrolled", esPres: "Inscribirse / Matricularse", esPast: "Se inscribió / Se matriculó", esPart: "Inscrito / Matriculado" },
  { type: "regular", sound: "d", base: "Register", past: "Registered", participle: "Registered", esPres: "Registrarse / Inscribirse", esPast: "Se registró / Se inscribió", esPart: "Registrado / Inscrito" },
  { type: "regular", sound: "d", base: "Interview", past: "Interviewed", participle: "Interviewed", esPres: "Entrevistar", esPast: "Entrevistó", esPart: "Entrevistado" },
  { type: "regular", sound: "d", base: "Fire", past: "Fired", participle: "Fired", esPres: "Despedir", esPast: "Despidió", esPart: "Despedido" },
  { type: "regular", sound: "id", base: "Promote", past: "Promoted", participle: "Promoted", esPres: "Ascender / Promover", esPast: "Ascendió / Promovió", esPart: "Ascendido / Promovido" },
  { type: "regular", sound: "d", base: "Retire", past: "Retired", participle: "Retired", esPres: "Jubilarse / Retirarse", esPast: "Se jubiló / Se retiró", esPart: "Jubilado / Retirado" },
  { type: "regular", sound: "d", base: "Resign", past: "Resigned", participle: "Resigned", esPres: "Renunciar / Dimitir", esPast: "Renunció / Dimitió", esPart: "Renunciado / Dimitido" },
  { type: "regular", sound: "id", base: "Negotiate", past: "Negotiated", participle: "Negotiated", esPres: "Negociar", esPast: "Negoció", esPart: "Negociado" },
  { type: "regular", sound: "d", base: "Sign", past: "Signed", participle: "Signed", esPres: "Firmar", esPast: "Firmó", esPart: "Firmado" },
  { type: "regular", sound: "d", base: "Define", past: "Defined", participle: "Defined", esPres: "Definir", esPast: "Definió", esPart: "Definido" },
  { type: "regular", sound: "d", base: "Analyze", past: "Analyzed", participle: "Analyzed", esPres: "Analizar", esPast: "Analizó", esPart: "Analizado" },
  { type: "regular", sound: "id", base: "Contrast", past: "Contrasted", participle: "Contrasted", esPres: "Contrastar", esPast: "Contrastó", esPart: "Contrastado" },
  { type: "regular", sound: "id", base: "Debate", past: "Debated", participle: "Debated", esPres: "Debatir", esPast: "Debatió", esPart: "Debatido" },
  { type: "regular", sound: "t", base: "Research", past: "Researched", participle: "Researched", esPres: "Investigar", esPast: "Investigó", esPart: "Investigado" },
  { type: "regular", sound: "id", base: "Investigate", past: "Investigated", participle: "Investigated", esPres: "Investigar", esPast: "Investigó", esPart: "Investigado" },
  { type: "regular", sound: "d", base: "Observe", past: "Observed", participle: "Observed", esPres: "Observar", esPast: "Observó", esPart: "Observado" },
  { type: "regular", sound: "id", base: "Experiment", past: "Experimented", participle: "Experimented", esPres: "Experimentar", esPast: "Experimentó", esPart: "Experimentado" },
  { type: "regular", sound: "id", base: "Conclude", past: "Concluded", participle: "Concluded", esPres: "Concluir", esPast: "Concluyó", esPart: "Concluido" },
  { type: "regular", sound: "id", base: "Calculate", past: "Calculated", participle: "Calculated", esPres: "Calcular", esPast: "Calculó", esPart: "Calculado" },
  { type: "regular", sound: "d", base: "Weigh", past: "Weighed", participle: "Weighed", esPres: "Pesar", esPast: "Pesó", esPart: "Pesado" },
  { type: "regular", sound: "id", base: "Estimate", past: "Estimated", participle: "Estimated", esPres: "Estimar / Calcular", esPast: "Estimó / Calculó", esPart: "Estimado / Calculado" },
  { type: "regular", sound: "t", base: "Guess", past: "Guessed", participle: "Guessed", esPres: "Adivinar / Suponer", esPast: "Adivinó / Supuso", esPart: "Adivinado / Supuesto" },
  { type: "regular", sound: "d", base: "Schedule", past: "Scheduled", participle: "Scheduled", esPres: "Programar / Agendar", esPast: "Programó / Agendó", esPart: "Programado / Agendado" },
  { type: "regular", sound: "d", base: "Arrange", past: "Arranged", participle: "Arranged", esPres: "Organizar / Arreglar", esPast: "Organizó / Arregló", esPart: "Organizado / Arreglado" },

  // ─── DINERO Y NEGOCIOS ───────────────────────────────────────────
  { type: "regular", sound: "t", base: "Wrap", past: "Wrapped", participle: "Wrapped", esPres: "Envolver", esPast: "Envolvió", esPart: "Envuelto" },
  { type: "regular", sound: "t", base: "Unwrap", past: "Unwrapped", participle: "Unwrapped", esPres: "Desenvolver", esPast: "Desenvolvió", esPart: "Desenvuelto" },
  { type: "regular", sound: "t", base: "Ship", past: "Shipped", participle: "Shipped", esPres: "Enviar / Despachar", esPast: "Envió / Despachó", esPart: "Enviado / Despachado" },
  { type: "regular", sound: "d", base: "Package", past: "Packaged", participle: "Packaged", esPres: "Empaquetar", esPast: "Empaquetó", esPart: "Empaquetado" },
  { type: "regular", sound: "t", base: "Purchase", past: "Purchased", participle: "Purchased", esPres: "Comprar / Adquirir", esPast: "Compró / Adquirió", esPart: "Comprado / Adquirido" },
  { type: "regular", sound: "t", base: "Lease", past: "Leased", participle: "Leased", esPres: "Arrendar", esPast: "Arrendó", esPart: "Arrendado" },
  { type: "regular", sound: "id", base: "Refund", past: "Refunded", participle: "Refunded", esPres: "Reembolsar", esPast: "Reembolsó", esPart: "Reembolsado" },
  { type: "regular", sound: "id", base: "Discount", past: "Discounted", participle: "Discounted", esPres: "Descontar / Rebajar", esPast: "Descontó / Rebajó", esPart: "Descontado / Rebajado" },
  { type: "regular", sound: "d", base: "Bargain", past: "Bargained", participle: "Bargained", esPres: "Regatear", esPast: "Regateó", esPart: "Regateado" },
  { type: "regular", sound: "id", base: "Budget", past: "Budgeted", participle: "Budgeted", esPres: "Presupuestar", esPast: "Presupuestó", esPart: "Presupuestado" },
  { type: "regular", sound: "id", base: "Donate", past: "Donated", participle: "Donated", esPres: "Donar", esPast: "Donó", esPart: "Donado" },
  { type: "regular", sound: "id", base: "Fund", past: "Funded", participle: "Funded", esPres: "Financiar", esPast: "Financió", esPart: "Financiado" },
  { type: "regular", sound: "d", base: "Sponsor", past: "Sponsored", participle: "Sponsored", esPres: "Patrocinar", esPast: "Patrocinó", esPart: "Patrocinado" },
  { type: "regular", sound: "t", base: "Tax", past: "Taxed", participle: "Taxed", esPres: "Gravar / Cobrar impuestos", esPast: "Gravó / Cobró impuestos", esPart: "Gravado" },
  { type: "regular", sound: "d", base: "Bill", past: "Billed", participle: "Billed", esPres: "Facturar", esPast: "Facturó", esPart: "Facturado" },
  { type: "regular", sound: "d", base: "Owe", past: "Owed", participle: "Owed", esPres: "Deber", esPast: "Debió", esPart: "Debido" },
  { type: "regular", sound: "d", base: "Loan", past: "Loaned", participle: "Loaned", esPres: "Prestar", esPast: "Prestó", esPart: "Prestado" },
  { type: "regular", sound: "d", base: "Transfer", past: "Transferred", participle: "Transferred", esPres: "Transferir", esPast: "Transfirió", esPart: "Transferido" },

  // ─── VIAJES Y TRANSPORTE ─────────────────────────────────────────
  { type: "regular", sound: "id", base: "Depart", past: "Departed", participle: "Departed", esPres: "Partir / Salir", esPast: "Partió / Salió", esPart: "Partido / Salido" },
  { type: "regular", sound: "id", base: "Land", past: "Landed", participle: "Landed", esPres: "Aterrizar", esPast: "Aterrizó", esPart: "Aterrizado" },
  { type: "regular", sound: "id", base: "Board", past: "Boarded", participle: "Boarded", esPres: "Abordar / Embarcar", esPast: "Abordó / Embarcó", esPart: "Abordado / Embarcado" },
  { type: "regular", sound: "d", base: "Reserve", past: "Reserved", participle: "Reserved", esPres: "Reservar", esPast: "Reservó", esPart: "Reservado" },
  { type: "regular", sound: "t", base: "Book", past: "Booked", participle: "Booked", esPres: "Reservar", esPast: "Reservó", esPart: "Reservado" },
  { type: "regular", sound: "d", base: "Cancel", past: "Cancelled", participle: "Cancelled", esPres: "Cancelar", esPast: "Canceló", esPart: "Cancelado" },
  { type: "regular", sound: "d", base: "Confirm", past: "Confirmed", participle: "Confirmed", esPres: "Confirmar", esPast: "Confirmó", esPart: "Confirmado" },
  { type: "regular", sound: "t", base: "Pack", past: "Packed", participle: "Packed", esPres: "Empacar / Hacer las maletas", esPast: "Empacó / Hizo las maletas", esPart: "Empacado" },
  { type: "regular", sound: "t", base: "Unpack", past: "Unpacked", participle: "Unpacked", esPres: "Desempacar", esPast: "Desempacó", esPart: "Desempacado" },
  { type: "regular", sound: "id", base: "Load", past: "Loaded", participle: "Loaded", esPres: "Cargar", esPast: "Cargó", esPart: "Cargado" },
  { type: "regular", sound: "id", base: "Unload", past: "Unloaded", participle: "Unloaded", esPres: "Descargar", esPast: "Descargó", esPart: "Descargado" },
  { type: "regular", sound: "t", base: "Park", past: "Parked", participle: "Parked", esPres: "Estacionar / Aparcar", esPast: "Estacionó / Aparcó", esPart: "Estacionado / Aparcado" },
  { type: "regular", sound: "d", base: "Tow", past: "Towed", participle: "Towed", esPres: "Remolcar", esPast: "Remolcó", esPart: "Remolcado" },
  { type: "regular", sound: "d", base: "Fuel", past: "Fueled", participle: "Fueled", esPres: "Repostar / Abastecer de combustible", esPast: "Repostó / Abasteció", esPart: "Repostado" },
  { type: "regular", sound: "t", base: "Brake", past: "Braked", participle: "Braked", esPres: "Frenar", esPast: "Frenó", esPart: "Frenado" },
  { type: "regular", sound: "d", base: "Signal", past: "Signaled", participle: "Signaled", esPres: "Señalizar / Indicar", esPast: "Señalizó / Indicó", esPart: "Señalizado / Indicado" },
  { type: "regular", sound: "d", base: "Merge", past: "Merged", participle: "Merged", esPres: "Fusionar / Incorporarse (al tráfico)", esPast: "Fusionó / Se incorporó", esPart: "Fusionado / Incorporado" },
  { type: "regular", sound: "t", base: "Honk", past: "Honked", participle: "Honked", esPres: "Tocar la bocina", esPast: "Tocó la bocina", esPart: "Tocado la bocina" },

  // ─── COCINA ───────────────────────────────────────────────────
  { type: "regular", sound: "t", base: "Bake", past: "Baked", participle: "Baked", esPres: "Hornear", esPast: "Horneó", esPart: "Horneado" },
  { type: "regular", sound: "d", base: "Boil", past: "Boiled", participle: "Boiled", esPres: "Hervir", esPast: "Hirvió", esPart: "Hervido" },
  { type: "regular", sound: "d", base: "Fry", past: "Fried", participle: "Fried", esPres: "Freír", esPast: "Frio", esPart: "Frito" },
  { type: "regular", sound: "d", base: "Grill", past: "Grilled", participle: "Grilled", esPres: "Asar a la parrilla", esPast: "Asó a la parrilla", esPart: "Asado a la parrilla" },
  { type: "regular", sound: "id", base: "Roast", past: "Roasted", participle: "Roasted", esPres: "Asar / Tostar", esPast: "Asó / Tostó", esPart: "Asado / Tostado" },
  { type: "regular", sound: "t", base: "Chop", past: "Chopped", participle: "Chopped", esPres: "Picar / Cortar", esPast: "Picó / Cortó", esPart: "Picado / Cortado" },
  { type: "regular", sound: "d", base: "Peel", past: "Peeled", participle: "Peeled", esPres: "Pelar", esPast: "Peló", esPart: "Pelado" },
  { type: "regular", sound: "d", base: "Stir", past: "Stirred", participle: "Stirred", esPres: "Revolver / Remover", esPast: "Revolvió / Removió", esPart: "Revuelto / Removido" },
  { type: "regular", sound: "id", base: "Blend", past: "Blended", participle: "Blended", esPres: "Licuar / Mezclar", esPast: "Licuó / Mezcló", esPart: "Licuado / Mezclado" },
  { type: "regular", sound: "d", base: "Season", past: "Seasoned", participle: "Seasoned", esPres: "Sazonar / Condimentar", esPast: "Sazonó / Condimentó", esPart: "Sazonado / Condimentado" },
  { type: "regular", sound: "id", base: "Taste", past: "Tasted", participle: "Tasted", esPres: "Probar / Saborear", esPast: "Probó / Saboreó", esPart: "Probado / Saboreado" },
  { type: "regular", sound: "t", base: "Garnish", past: "Garnished", participle: "Garnished", esPres: "Adornar / Decorar (un plato)", esPast: "Adornó / Decoró", esPart: "Adornado / Decorado" },

  // ─── CLIMA ───────────────────────────────────────────────────
  { type: "regular", sound: "d", base: "Snow", past: "Snowed", participle: "Snowed", esPres: "Nevar", esPast: "Nevó", esPart: "Nevado" },

];
